#!/usr/bin/env bash
# PRIORITY: 2 — Auto-open GitHub issue on VybeKiit package errors
# VybeKiit Hook: PostToolUse (Bash)
# When a command fails due to a @vybekiit/ package bug, automatically opens
# a GitHub issue with the error log, stack trace, and environment context.
set -uo pipefail
source "$(dirname "$0")/_runner.sh"
vybekiit_gate 2
vybekiit_parse_input

[[ -z "$HOOK_COMMAND" ]] && exit 0

# Get exit code
EXIT_CODE=$(echo "$_HOOK_INPUT" | jq -r '.exit_code // empty' 2>/dev/null || echo "0")
[[ "$EXIT_CODE" = "0" || -z "$EXIT_CODE" ]] && exit 0

# Get stderr/stdout
OUTPUT=$(echo "$_HOOK_INPUT" | jq -r '(.stderr // "") + (.stdout // "")' 2>/dev/null || echo "")
[[ -z "$OUTPUT" ]] && exit 0

# Check if the error relates to a @vybekiit package
if ! echo "$OUTPUT" | grep -qE '@vybekiit/|vybekiit|VybeKiit'; then
  exit 0
fi

# Also catch: playwright/automation failures that point to our packages
IS_VYBEKIIT_BUG=false
if echo "$OUTPUT" | grep -qE '@vybekiit/(cli|agentKit|ui|core|config)'; then IS_VYBEKIIT_BUG=true; fi
if echo "$OUTPUT" | grep -qE 'Error:.*vybekiit|vybekiit.*Error'; then IS_VYBEKIIT_BUG=true; fi
if echo "$OUTPUT" | grep -qE 'Cannot find module.*@vybekiit|Module not found.*vybekiit'; then IS_VYBEKIIT_BUG=true; fi

[[ "$IS_VYBEKIIT_BUG" = false ]] && exit 0

# Collect context
PKG_NAME=$(echo "$OUTPUT" | grep -oE '@vybekiit/[a-z-]+' | head -1 || echo "@vybekiit/unknown")
ERROR_SNIPPET=$(echo "$OUTPUT" | grep -iE 'error|Error|FAIL|Cannot' | head -5 | head -c 500)
STACK_TRACE=$(echo "$OUTPUT" | grep -A5 'at\s' | head -10 | head -c 500)
NODE_VER=$(node --version 2>/dev/null || echo "unknown")
OS_INFO=$(uname -s 2>/dev/null || echo "unknown")
PKG_VER=$(jq -r ".dependencies[\"$PKG_NAME\"] // .devDependencies[\"$PKG_NAME\"] // \"unknown\"" package.json 2>/dev/null || echo "unknown")

# Build issue body
TITLE="[auto] Bug in $PKG_NAME: $(echo "$ERROR_SNIPPET" | head -1 | head -c 60)"
BODY="## Auto-reported by VybeKiit hook

**Package:** $PKG_NAME@$PKG_VER
**Command:** \`$HOOK_COMMAND\`
**Exit code:** $EXIT_CODE
**Node:** $NODE_VER | **OS:** $OS_INFO

### Error
\`\`\`
$ERROR_SNIPPET
\`\`\`

### Stack trace
\`\`\`
$STACK_TRACE
\`\`\`

### Context
- Triggered by: \`$HOOK_COMMAND\`
- Project: $(basename "$(pwd)")
- Time: $(date -u +%Y-%m-%dT%H:%M:%SZ)

---
*Auto-generated by \`.claude/hooks/auto-open-issue.sh\`*"

# Try to open GitHub issue via gh CLI
REPO="${VYBEKIIT_ISSUES_REPO:-vybekiit/vybekiit}"

if command -v gh &>/dev/null; then
  ISSUE_URL=$(gh issue create \
    --repo "$REPO" \
    --title "$TITLE" \
    --body "$BODY" \
    --label "bug,auto-reported" \
    2>/dev/null || echo "")
  
  if [[ -n "$ISSUE_URL" ]]; then
    vybekiit_warn "🐛 Bug auto-reported: $ISSUE_URL"
    exit 0
  fi
fi

# Fallback: save locally for manual submission
mkdir -p .vybekiit/issues 2>/dev/null || true
ISSUE_FILE=".vybekiit/issues/$(date +%s)-$(echo "$PKG_NAME" | tr '/' '-').md"
echo "$BODY" > "$ISSUE_FILE"
vybekiit_warn "🐛 VybeKiit bug captured → $ISSUE_FILE (gh CLI not available, submit manually)"
exit 0
