import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import type { CwsListing } from '../schema';
import type { VerbContext } from '../types';

import { isCwsAllRegions } from '../regions';
import { readListingState } from './readListingState';

/**
 * Bootstrap or refresh `extensions/<name>/cws-listing.ts` from the live
 * Chrome Web Store state.
 *
 * Why this is the first verb a developer should run on an extension: until
 * a `cws-listing.ts` file exists, `updateListing` has no source-of-truth
 * to push from. A first-time `update-listing` would push an empty/default
 * listing and overwrite the developer's real CWS data — the exact
 * "no deletion" failure mode the auth model is meant to prevent.
 *
 * Idempotent: running `importListing` repeatedly produces the same file
 * contents (modulo CWS state changes). Safe to re-run after Google adds a
 * field — the next push picks it up.
 */
export async function importListing(ctx: VerbContext): Promise<{ filePath: string }> {
  const log = ctx.log ?? console;
  const listing = await readListingState(ctx);

  const filePath = resolve(ctx.repoRoot, ctx.extension.dir, 'cws-listing.ts');
  await writeFile(filePath, renderListingFile(listing), 'utf8');

  log.log(`[cws] wrote ${filePath}`);
  return { filePath };
}

/** Renders listing data while keeping the repeated all-regions map shared. */
function renderListingBody(listing: CwsListing, usesAllRegions: boolean): string {
  if (!usesAllRegions) return JSON.stringify(listing, null, 2);

  const placeholder = '__CWS_ALL_REGIONS__';
  const body = JSON.stringify(
    {
      ...listing,
      distribution: {
        ...listing.distribution,
        regions: placeholder,
      },
    },
    null,
    2,
  );

  return body.replace(`"regions": "${placeholder}"`, '"regions": CWS_ALL_REGIONS');
}

/**
 * Render a `CwsListing` value as a typed TS module. The file imports the
 * schema's TS type and uses `satisfies` so changes to the schema surface
 * as compile errors at the listing site, not at push time.
 *
 * Why we emit TS instead of JSON: developers and agents author this file.
 * TS gives them autocomplete and inline schema docs; JSON is a regression.
 * The trade-off is that we can't `JSON.parse` it back at push time — we
 * import it dynamically, which `updateListing` does.
 */
function renderListingFile(listing: CwsListing): string {
  const usesAllRegions = isCwsAllRegions(listing.distribution.regions);
  const body = renderListingBody(listing, usesAllRegions);
  const regionsImport = usesAllRegions
    ? "import { CWS_ALL_REGIONS } from '@vybekiit/extension-publish/regions';\n"
    : '';

  return `import type { CwsListing } from '@vybekiit/extension-publish/schema';
${regionsImport}

/**
 * Source of truth for this extension's Chrome Web Store listing.
 *
 * Generated by \`pnpm cws import-listing\`. Edit by hand or via agent;
 * push with \`pnpm cws update-listing <key>\`. The push aborts on drift —
 * if you also edited fields directly in the dev console, re-import first.
 */
const listing = ${body} satisfies CwsListing;

export default listing;
`;
}
