/** Browser-only LS selector field keys — nested taxonomy for the product editor. */
export const LS_DRAFT_FIELDS = [
  'product.createButton',
  'product.nameInput',
  'product.descriptionInput',
  'product.pricing.single.option',
  'product.pricing.subscription.option',
  'product.pricing.leadMagnet.option',
  'product.pricing.payWhatYouWant.option',
  'product.pricing.priceInput',
  'product.pricing.taxCategorySelect',
  'product.pricing.pricingModelSelect',
  'product.pricing.subscription.intervalSelect',
  'product.pricing.payWhatYouWant.minPriceInput',
  'product.pricing.payWhatYouWant.suggestedPriceInput',
  'product.media.uploadInput',
  'product.files.uploadInput',
  'product.variants.addButton',
  'product.actions.saveDraftButton',
  'product.actions.publishButton',
  'product.actions.menuTrigger',
  'product.actions.editMenuItem',
  'product.actions.shareMenuItem',
  'product.actions.previewMenuItem',
  'product.actions.unpublishMenuItem',
  'product.actions.duplicateMenuItem',
  'product.actions.copyToTestModeMenuItem',
  'product.actions.copyIdMenuItem',
  'product.actions.deleteMenuItem',
  'product.settings.licenseKeysToggle',
  'product.settings.storefrontDisplayToggle',
  'product.settings.confirmationModalToggle',
  'product.settings.emailReceiptToggle',
  'product.confirmation.titleInput',
  'product.confirmation.messageInput',
  'product.confirmation.buttonTextInput',
  'product.confirmation.buttonLinkInput',
  'product.emailReceipt.thankYouNoteInput',
  'product.emailReceipt.buttonTextInput',
  'product.emailReceipt.buttonLinkInput',
  'dashboard.storeId',
  /** Probe/classification only — production scrapes variant ID from product page HTML. */
  'dashboard.variantId',
] as const;

export type LsDraftFieldKey = (typeof LS_DRAFT_FIELDS)[number];
