'use client';

import { PageContainer } from '@library/components/shell/PageContainer';
import {
  CHANGELOG_DATA,
  type ChangelogCommit,
  type RoadmapItem,
} from '@library/data/changelog.generated';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@vybekiit/ui/accordion';
import { Badge } from '@vybekiit/ui/badge';
import { Button } from '@vybekiit/ui/button';
import { VybeKitMark } from '@vybekiit/ui/vybekiit-logo';
import {
  CheckCircle2,
  Circle,
  Code,
  ExternalLink,
  FlaskConical,
  GitCommit,
  type LucideIcon,
  Milestone,
  PauseCircle,
  RefreshCw,
  Rocket,
  Tag,
} from 'lucide-react';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { cn } from '@/lib/utils';

const { legend, releases, roadmap } = CHANGELOG_DATA;

const SECTION_ORDER = ['Added', 'Changed', 'Fixed', 'Removed', 'Other'] as const;

const SECTION_STYLE: Record<string, string> = {
  Added: 'border-emerald-500/30 bg-emerald-500/10 text-emerald-600',
  Changed: 'border-violet-500/30 bg-violet-500/10 text-violet-600',
  Fixed: 'border-amber-500/30 bg-amber-500/10 text-amber-600',
  Removed: 'border-red-500/30 bg-red-500/10 text-red-600',
  Other: 'border-slate-500/30 bg-slate-500/10 text-slate-500',
};

/**
 * Status mark (ADR-0039 live-work legend) rendered as an icon from the shared lucide SSOT.
 * Keyed by the exact emoji the generator emits so the data stays the single source of truth while
 * the UI shows a proper SVG instead of a raw emoji.
 */
const MARK_META: Record<string, { readonly Icon: LucideIcon; readonly className: string }> = {
  '✅': { Icon: CheckCircle2, className: 'text-emerald-600' }, // shipped + confirmed
  '🔄': { Icon: RefreshCw, className: 'text-blue-600' }, // in progress
  '⬜': { Icon: Circle, className: 'text-muted-foreground' }, // not started
  '🅿️': { Icon: PauseCircle, className: 'text-slate-500' }, // parked
  '🧪': { Icon: FlaskConical, className: 'text-amber-600' }, // needs network / secrets
  '💻': { Icon: Code, className: 'text-violet-600' }, // pure code
};

const FALLBACK_MARK = { Icon: Circle, className: 'text-muted-foreground' } as const;

/** Resolve the icon + tint for a status mark, falling back to an empty circle for unknown marks. */
const markMeta = (mark: string) => MARK_META[mark] ?? FALLBACK_MARK;

/** Stage order for the roadmap accordion; mirrors the generator's ROADMAP_LABELS so a stage can't drift off-list. */
const STAGE_ORDER = ['v1.0', 'v2', 'v3', 'money-pipeline', 'needs-secrets', 'enhancement'];
const stageRank = (stage: string) => STAGE_ORDER.indexOf(stage) + 1 || 99;

const PR_BASE = 'https://github.com/VybeKiit/vybekiit/pull/';

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

/** Format an ISO `YYYY-MM-DD` string deterministically (no locale/timezone drift across SSR + client). */
const formatReleaseDate = (iso: string) => {
  const [year, month, day] = iso.split('-').map(Number);
  return month >= 1 && month <= 12 ? `${MONTHS[month - 1]} ${day}, ${year}` : iso;
};

const NUMERIC_VERSION_RE = /^\d/;

/** Prefix numeric versions with "v" for display; leave word versions like "Unreleased" untouched. */
const displayVersion = (version: string) =>
  NUMERIC_VERSION_RE.test(version) ? `v${version}` : version;

/**
 * The maintainer "Kit changelog" release board (ADR-0041): shipped changes per release plus the
 * roadmap (done / gated / not started). Data is generated by generateChangelog.mjs — never hand-edited.
 * Reuses the shared @vybekiit/ui vocabulary (collapsible Accordion panels, Badge) and the shared
 * lucide icon SSOT for every status mark.
 *
 * @returns The changelog board route element.
 * @example
 * const element = <ChangelogBoardRoute />;
 */
const ChangelogBoardRoute = () => {
  const [area, setArea] = useState('all');

  const areas = useMemo(() => {
    const scopes = new Set<string>();
    for (const release of releases) {
      for (const commit of release.commits) {
        if (commit.scope) {
          scopes.add(commit.scope);
        }
      }
    }
    return ['all', ...[...scopes].sort((a, b) => a.localeCompare(b))];
  }, []);

  const stages = useMemo(() => {
    const byStage = new Map<string, RoadmapItem[]>();
    for (const item of roadmap) {
      const bucket = byStage.get(item.stage) ?? [];
      bucket.push(item);
      byStage.set(item.stage, bucket);
    }
    return [...byStage.entries()].sort(([a], [b]) => stageRank(a) - stageRank(b));
  }, []);

  const unreleased = releases.find((release) => release.version === 'Unreleased');
  // "Done" = a closed roadmap issue (the generator stamps closed issues ✅). Count off the semantic
  // `state` field so the tally never depends on a presentation glyph.
  const doneCount = roadmap.filter((item) => item.state === 'closed').length;
  const matchesArea = (commit: ChangelogCommit) => area === 'all' || commit.scope === area;

  return (
    <PageContainer size="default">
      <header className="mb-8">
        <Badge className="mb-2 w-fit" variant="secondary">
          Maintainer · Kit changelog
        </Badge>
        <h1 className="font-bold text-3xl tracking-tight md:text-4xl">VybeKiit release board</h1>
        <p className="mt-1 max-w-2xl text-muted-foreground">
          Auto-generated from git history + the GitHub Issues roadmap (ADR-0041). Each release lists
          shipped changes; the roadmap below tracks what is done, gated, or not started.
        </p>
        <div className="mt-4 flex flex-wrap gap-2 text-sm">
          <span className="inline-flex items-center gap-1 rounded-md border px-2 py-1">
            <Tag className="h-3.5 w-3.5" /> {releases.length} releases
          </span>
          <span className="inline-flex items-center gap-1 rounded-md border px-2 py-1">
            <Rocket className="h-3.5 w-3.5" /> {unreleased?.commits.length ?? 0} unreleased commits
          </span>
          <span className="inline-flex items-center gap-1 rounded-md border px-2 py-1">
            <Milestone className="h-3.5 w-3.5" /> {doneCount}/{roadmap.length} roadmap done
          </span>
        </div>
      </header>

      <section className="mb-10">
        <h2 className="mb-3 flex items-center gap-2 font-semibold text-xl">
          <Milestone className="h-5 w-5 text-primary" /> Roadmap
        </h2>
        <div className="mb-4 flex flex-wrap gap-x-4 gap-y-1 text-muted-foreground text-xs">
          {Object.entries(legend).map(([mark, description]) => {
            const { Icon, className } = markMeta(mark);
            return (
              <span key={mark} className="inline-flex items-center gap-1.5">
                <Icon aria-hidden="true" className={cn('h-3.5 w-3.5', className)} />
                {description}
              </span>
            );
          })}
        </div>
        <Accordion
          className="flex flex-col rounded-lg border"
          defaultValue={stages[0] ? [stages[0][0]] : []}
          type="multiple"
        >
          {stages.map(([stage, items]) => {
            const done = items.filter((item) => item.state === 'closed').length;
            return (
              <AccordionItem className="border-b px-4 last:border-b-0" key={stage} value={stage}>
                <AccordionTrigger>
                  <span className="flex flex-1 items-center gap-3 pr-3">
                    <span className="font-mono text-base">{stage}</span>
                    <Badge className="ml-auto font-normal" variant="outline">
                      {done}/{items.length}
                    </Badge>
                  </span>
                </AccordionTrigger>
                <AccordionContent className="space-y-1.5">
                  {items.map((item) => {
                    const { Icon, className } = markMeta(item.mark);
                    return (
                      <a
                        key={item.number}
                        className="flex items-start gap-2 rounded-md p-1 hover:bg-muted"
                        href={item.url}
                        rel="noreferrer"
                        target="_blank"
                      >
                        <Icon
                          aria-hidden="true"
                          className={cn('mt-0.5 h-4 w-4 shrink-0', className)}
                        />
                        <span className="text-sm leading-snug">
                          <span className="font-mono text-muted-foreground text-xs">
                            #{item.number}
                          </span>{' '}
                          {item.title}
                        </span>
                        <ExternalLink className="mt-1 ml-auto h-3 w-3 shrink-0 text-muted-foreground" />
                      </a>
                    );
                  })}
                </AccordionContent>
              </AccordionItem>
            );
          })}
        </Accordion>
      </section>

      <section>
        <div className="mb-4 flex flex-wrap items-center gap-2">
          <h2 className="flex items-center gap-2 font-semibold text-xl">
            <GitCommit className="h-5 w-5 text-primary" /> Changelog
          </h2>
          <div className="ml-auto flex flex-wrap gap-1">
            {areas.map((option) => (
              <Button
                key={option}
                onClick={() => setArea(option)}
                size="sm"
                type="button"
                variant={option === area ? 'secondary' : 'outline'}
              >
                {option === 'all' ? 'All areas' : option}
              </Button>
            ))}
          </div>
        </div>

        <Accordion
          className="flex flex-col rounded-lg border"
          defaultValue={releases[0] ? [releases[0].version] : []}
          type="multiple"
        >
          {releases.map((release) => {
            const filtered = release.commits.filter(matchesArea);
            const grouped = SECTION_ORDER.map((section) => ({
              section,
              commits: filtered.filter((commit) => commit.section === section),
            })).filter((group) => group.commits.length > 0);
            const ReleaseIcon = release.version === 'Unreleased' ? Rocket : Tag;

            return (
              <AccordionItem
                className="border-b px-4 last:border-b-0"
                key={release.version}
                value={release.version}
              >
                <AccordionTrigger>
                  <span className="flex flex-1 flex-wrap items-center gap-2 pr-3">
                    <ReleaseIcon
                      aria-hidden="true"
                      className={cn(
                        'h-4 w-4 shrink-0',
                        release.version === 'Unreleased' ? 'text-primary' : 'text-muted-foreground',
                      )}
                    />
                    <span className="font-semibold text-base">
                      {displayVersion(release.version)}
                    </span>
                    {release.date ? (
                      <span className="font-normal text-muted-foreground text-sm">
                        {formatReleaseDate(release.date)}
                      </span>
                    ) : (
                      <Badge variant="secondary">in progress</Badge>
                    )}
                    <Badge className="ml-auto font-normal text-xs" variant="outline">
                      {filtered.length} changes
                    </Badge>
                  </span>
                </AccordionTrigger>
                <AccordionContent>
                  {grouped.length === 0 ? (
                    <p className="text-muted-foreground text-sm">
                      No {area === 'all' ? '' : `${area} `}changes.
                    </p>
                  ) : (
                    <div className="space-y-3">
                      {grouped.map(({ section, commits }) => (
                        <div key={section}>
                          <Badge
                            className={cn('mb-1 font-normal', SECTION_STYLE[section])}
                            variant="outline"
                          >
                            {section}
                          </Badge>
                          <ul className="space-y-1">
                            {commits.map((commit) => (
                              <li
                                className="text-sm leading-snug"
                                key={`${commit.pr ?? 'x'}-${commit.description}`}
                              >
                                {commit.scope ? (
                                  <span className="font-mono text-muted-foreground text-xs">
                                    {commit.scope}:{' '}
                                  </span>
                                ) : null}
                                {commit.description}
                                {commit.breaking ? (
                                  <Badge
                                    className="ml-1 border-red-500/40 text-red-600 text-xs"
                                    variant="outline"
                                  >
                                    breaking
                                  </Badge>
                                ) : null}
                                {commit.pr ? (
                                  <a
                                    className="ml-1 text-muted-foreground text-xs hover:underline"
                                    href={`${PR_BASE}${commit.pr}`}
                                    rel="noreferrer"
                                    target="_blank"
                                  >
                                    #{commit.pr}
                                  </a>
                                ) : null}
                              </li>
                            ))}
                          </ul>
                        </div>
                      ))}
                    </div>
                  )}
                </AccordionContent>
              </AccordionItem>
            );
          })}
        </Accordion>
      </section>

      <footer className="mt-16 flex flex-col gap-4 border-t pt-6 text-muted-foreground text-sm sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-center gap-2">
          <VybeKitMark className="h-5 w-5 text-foreground" />
          <span>
            VybeKiit · <span className="text-muted-foreground/80">ui.vybekiit.com</span>
          </span>
        </div>
        <nav className="flex flex-wrap items-center gap-x-4 gap-y-1">
          <a
            className="transition-colors hover:text-foreground"
            href="https://github.com/VybeKiit/vybekiit"
            rel="noreferrer"
            target="_blank"
          >
            GitHub
          </a>
          <Link className="transition-colors hover:text-foreground" href="/design-system">
            Design system
          </Link>
          <Link className="transition-colors hover:text-foreground" href="/pages">
            Recipes
          </Link>
          <span className="text-muted-foreground/70">Auto-generated · ADR-0041</span>
        </nav>
      </footer>
    </PageContainer>
  );
};

export default ChangelogBoardRoute;
