import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { isCwsAllRegions } from '@vybekiit/browserAutomation/domains/extension/regions';
import type { CwsListing } from '@vybekiit/browserAutomation/domains/extension/schema';
import { cwsListingPath } from '@vybekiit/browserAutomation/domains/extension/store';
import type { VerbContext } from '@vybekiit/browserAutomation/domains/extension/types';
import { readListingState } from './readListingState';

/**
 * Bootstrap or refresh `.vybekiit/store/extension/cws-listing.ts` from live CWS state.
 */
export async function importListing(ctx: VerbContext): Promise<{ filePath: string }> {
  const log = ctx.log ?? console;
  const listing = await readListingState(ctx);

  const filePath = cwsListingPath(ctx.repoRoot);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, renderListingFile(listing), 'utf8');

  log.log(`[cws] wrote ${filePath}`);
  return { filePath };
}

function renderListingBody(listing: CwsListing, usesAllRegions: boolean): string {
  if (!usesAllRegions) return JSON.stringify(listing, null, 2);

  const placeholder = '__CWS_ALL_REGIONS__';
  const body = JSON.stringify(
    {
      ...listing,
      distribution: {
        ...listing.distribution,
        regions: placeholder,
      },
    },
    null,
    2,
  );

  return body.replace(`"regions": "${placeholder}"`, '"regions": CWS_ALL_REGIONS');
}

function renderListingFile(listing: CwsListing): string {
  const usesAllRegions = isCwsAllRegions(listing.distribution.regions);
  const body = renderListingBody(listing, usesAllRegions);
  const regionsImport = usesAllRegions
    ? "import { CWS_ALL_REGIONS } from '@vybekiit/browser-automation/regions';\n"
    : '';

  return `import type { CwsListing } from '@vybekiit/browser-automation/schema';
${regionsImport}

/**
 * Source of truth for this extension's Chrome Web Store listing.
 *
 * Generated by \`vybekiit-automate extension import\`. Push with \`vybekiit-automate extension update\`.
 */
const listing = ${body} satisfies CwsListing;

export default listing;
`;
}
