import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { resolveVerbLogger } from '@vybekiit/browser-automation/core/verbLogger';
import { isCwsAllRegions } from '@vybekiit/browser-automation/domains/extension/regions';
import type { CwsListing } from '@vybekiit/browser-automation/domains/extension/schema';
import { cwsListingPath } from '@vybekiit/browser-automation/domains/extension/store';
import type { VerbContext } from '@vybekiit/browser-automation/domains/extension/types';
import { readListingState } from './readListingState';

/**
 * Bootstrap or refresh `.vybekiit/store/extension/cws-listing.ts` from live CWS state.
 *
 * @param ctx - Extension automation context with repo paths, auth state, and logging.
 * @returns The file path written to `.vybekiit/store/extension/cws-listing.ts`.
 * @example
 * const { filePath } = await importListing(ctx);
 */
export const importListing = async (ctx: VerbContext): Promise<{ filePath: string }> => {
  const log = resolveVerbLogger(ctx);
  const listing = await readListingState(ctx);

  const filePath = cwsListingPath(ctx.repoRoot);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, renderListingFile(listing), 'utf8');

  log.log(`[cws] wrote ${filePath}`);
  return { filePath };
};

/**
 * Render the listing object body for the generated source file.
 *
 * @param listing - Validated Chrome Web Store listing state.
 * @param usesAllRegions - Whether the generated file should import the all-regions constant.
 * @returns TypeScript expression text for the listing object.
 * @example
 * const body = renderListingBody(listing, true);
 */
const renderListingBody = (listing: CwsListing, usesAllRegions: boolean): string => {
  if (!usesAllRegions) {
    return JSON.stringify(listing, null, 2);
  }

  const placeholder = '__CWS_ALL_REGIONS__';
  const body = JSON.stringify(
    {
      ...listing,
      distribution: {
        ...listing.distribution,
        regions: placeholder,
      },
    },
    null,
    2,
  );

  return body.replace(`"regions": "${placeholder}"`, '"regions": CWS_ALL_REGIONS');
};

/**
 * Render the full generated `cws-listing.ts` module.
 *
 * @param listing - Validated Chrome Web Store listing state.
 * @returns TypeScript module text containing the listing source of truth.
 * @example
 * const source = renderListingFile(listing);
 */
const renderListingFile = (listing: CwsListing): string => {
  const usesAllRegions = isCwsAllRegions(listing.distribution.regions);
  const body = renderListingBody(listing, usesAllRegions);
  const regionsImport = usesAllRegions
    ? "import { CWS_ALL_REGIONS } from '@vybekiit/browser-automation/regions';\n"
    : '';

  return `import type { CwsListing } from '@vybekiit/browser-automation/schema';
${regionsImport}

/**
 * Source of truth for this extension's Chrome Web Store listing.
 *
 * Generated by \`vybekiit-automate extension import\`. Push with \`vybekiit-automate extension update\`.
 */
export const listing = ${body} satisfies CwsListing;
`;
};
