import type { CwsListing } from './schema';

/** Region map used when a Chrome Web Store item is available in every supported region. */
export const CWS_ALL_REGIONS = {
  Albania: true,
  Algeria: true,
  'All regions': true,
  'All unlisted regions': true,
  'American Samoa': true,
  Angola: true,
  'Antigua & Barbuda': true,
  Argentina: true,
  Armenia: true,
  Aruba: true,
  Australia: true,
  Austria: true,
  Azerbaijan: true,
  Bahamas: true,
  Bahrain: true,
  Bangladesh: true,
  Belarus: true,
  Belgium: true,
  Belize: true,
  Benin: true,
  Bolivia: true,
  'Bosnia & Herzegovina': true,
  Botswana: true,
  Brazil: true,
  Bulgaria: true,
  Cambodia: true,
  Cameroon: true,
  Canada: true,
  'Caribbean Netherlands': true,
  Chile: true,
  China: true,
  Colombia: true,
  'Costa Rica': true,
  'Côte d’Ivoire': true,
  Croatia: true,
  Cuba: true,
  Cyprus: true,
  Czechia: true,
  Denmark: true,
  Dominica: true,
  'Dominican Republic': true,
  Ecuador: true,
  Egypt: true,
  'El Salvador': true,
  Estonia: true,
  Fiji: true,
  Finland: true,
  France: true,
  Gabon: true,
  Georgia: true,
  Germany: true,
  Ghana: true,
  Gibraltar: true,
  Greece: true,
  Guam: true,
  Guatemala: true,
  Guinea: true,
  'Guinea-Bissau': true,
  Haiti: true,
  Honduras: true,
  'Hong Kong': true,
  Hungary: true,
  Iceland: true,
  India: true,
  Indonesia: true,
  Iran: true,
  Iraq: true,
  Ireland: true,
  Israel: true,
  Italy: true,
  Jamaica: true,
  Japan: true,
  Jordan: true,
  Kazakhstan: true,
  Kenya: true,
  Kuwait: true,
  Kyrgyzstan: true,
  Laos: true,
  Latvia: true,
  Lebanon: true,
  Liechtenstein: true,
  Lithuania: true,
  Luxembourg: true,
  Malaysia: true,
  Mali: true,
  Malta: true,
  'Marshall Islands': true,
  Mauritius: true,
  Mexico: true,
  Moldova: true,
  Monaco: true,
  Morocco: true,
  Mozambique: true,
  'Myanmar (Burma)': true,
  Namibia: true,
  Nepal: true,
  Netherlands: true,
  'New Zealand': true,
  Nicaragua: true,
  Niger: true,
  Nigeria: true,
  'Northern Mariana Islands': true,
  'North Korea': true,
  Norway: true,
  Oman: true,
  Pakistan: true,
  Palau: true,
  Panama: true,
  'Papua New Guinea': true,
  Paraguay: true,
  Peru: true,
  Philippines: true,
  Poland: true,
  Portugal: true,
  'Puerto Rico': true,
  Qatar: true,
  Romania: true,
  Russia: true,
  Rwanda: true,
  Samoa: true,
  'San Marino': true,
  'Saudi Arabia': true,
  Senegal: true,
  Serbia: true,
  Singapore: true,
  Slovakia: true,
  Slovenia: true,
  'South Africa': true,
  'South Korea': true,
  Spain: true,
  'Sri Lanka': true,
  Sweden: true,
  Switzerland: true,
  Syria: true,
  Taiwan: true,
  Tajikistan: true,
  Tanzania: true,
  Thailand: true,
  Togo: true,
  'Trinidad & Tobago': true,
  Tunisia: true,
  Türkiye: true,
  Turkmenistan: true,
  Uganda: true,
  Ukraine: true,
  'United Arab Emirates': true,
  'United Kingdom': true,
  'United States': true,
  Uruguay: true,
  Uzbekistan: true,
  Venezuela: true,
  Vietnam: true,
  Yemen: true,
  Zambia: true,
  Zimbabwe: true,
} satisfies CwsListing['distribution']['regions'];

/**
 * Check whether a listing region map is the canonical all-regions selection.
 *
 * @param regions - CWS listing region map to compare.
 * @returns True when every canonical region is enabled and no extra region exists.
 * @example
 * const allRegions = isCwsAllRegions(CWS_ALL_REGIONS);
 */
export const isCwsAllRegions = (regions: CwsListing['distribution']['regions']): boolean => {
  const entries = Object.entries(CWS_ALL_REGIONS);
  if (Object.keys(regions).length !== entries.length) {
    return false;
  }

  return entries.every(([region, isEnabled]) => regions[region] === isEnabled);
};
