#!/usr/bin/env bash
# PRIORITY: 3 — Auto-file feature request when a missing skill is loaded
# VybeKiit Hook: PostToolUse (Bash)
# When Claude tries to load/read a skill that doesn't exist, this hook
# automatically opens a GitHub issue as a feature request for that skill.
set -uo pipefail
source "$(dirname "$0")/_runner.sh"
vybekiit_gate 3
vybekiit_parse_input

[[ -z "$HOOK_COMMAND" ]] && exit 0

# Detect attempts to read skill files that failed
EXIT_CODE=$(echo "$_HOOK_INPUT" | jq -r '.exit_code // empty' 2>/dev/null || echo "0")
STDERR=$(echo "$_HOOK_INPUT" | jq -r '.stderr // empty' 2>/dev/null || echo "")

# Only trigger on failure (exit != 0)
[[ "$EXIT_CODE" = "0" || -z "$EXIT_CODE" ]] && exit 0

# Patterns that indicate a skill load attempt
IS_SKILL_LOAD=false
SKILL_NAME=""

# Pattern 1: cat/read of .kiro/skills/X/SKILL.md
if echo "$HOOK_COMMAND" | grep -qE '(cat|head|less|bat)\s+.*\.kiro/skills/[^/]+'; then
  SKILL_NAME=$(echo "$HOOK_COMMAND" | grep -oE '\.kiro/skills/([^/]+)' | sed -E 's|\.kiro/skills/||')
  IS_SKILL_LOAD=true
fi

# Pattern 2: ls/find of .kiro/skills/X/
if echo "$HOOK_COMMAND" | grep -qE '(ls|find|stat)\s+.*\.kiro/skills/[^/]+'; then
  SKILL_NAME=$(echo "$HOOK_COMMAND" | grep -oE '\.kiro/skills/([^/]+)' | sed -E 's|\.kiro/skills/||')
  IS_SKILL_LOAD=true
fi

# Pattern 3: cat .claude/skills/X or commands.md pattern
if echo "$HOOK_COMMAND" | grep -qE '(cat|head)\s+.*\.(claude|cursor)/skills/[^/]+'; then
  SKILL_NAME=$(echo "$HOOK_COMMAND" | grep -oE 'skills/([^/]+)' | head -1 | sed 's|skills/||')
  IS_SKILL_LOAD=true
fi

# Pattern 4: "No such file" error mentioning skills
if echo "$STDERR" | grep -qE 'No such file.*skill|skill.*not found|SKILL\.md.*No such'; then
  SKILL_NAME=$(echo "$STDERR" | grep -oE 'skills/([^/:"]+)' | head -1 | sed 's|skills/||')
  [[ -n "$SKILL_NAME" ]] && IS_SKILL_LOAD=true
fi

[[ "$IS_SKILL_LOAD" = false || -z "$SKILL_NAME" ]] && exit 0

# Deduplicate: check if we already filed for this skill recently
DEDUP_FILE=".vybekiit/requested-skills.log"
mkdir -p .vybekiit 2>/dev/null || true

if [[ -f "$DEDUP_FILE" ]] && grep -q "^${SKILL_NAME}$" "$DEDUP_FILE" 2>/dev/null; then
  # Already requested — don't spam
  exit 0
fi

# Record the request
echo "$SKILL_NAME" >> "$DEDUP_FILE"

# Build the issue
TITLE="[feature-request] Skill: ${SKILL_NAME}"
BODY="## Skill Request: \`${SKILL_NAME}\`

**Requested by:** Auto-detected during Claude Code session
**Context:** User or agent tried to load skill \`${SKILL_NAME}\` but it doesn't exist yet.

### What happened
- Command: \`${HOOK_COMMAND}\`
- Error: \`$(echo "$STDERR" | head -2 | head -c 200)\`
- Project: \`$(basename "$(pwd)")\`
- Time: $(date -u +%Y-%m-%dT%H:%M:%SZ)

### Suggested scope
A skill that provides guidance and tooling for **${SKILL_NAME}** workflows.

### Acceptance criteria
- [ ] \`.kiro/skills/${SKILL_NAME}/SKILL.md\` exists with clear description
- [ ] Skill has concrete, actionable instructions (not generic advice)
- [ ] Works with VybeKiit templates and conventions

---
*Auto-generated by \`.claude/hooks/auto-request-skill.sh\`*"

# Try GitHub issue
REPO="${VYBEKIIT_ISSUES_REPO:-vybekiit/vybekiit}"

if command -v gh &>/dev/null; then
  ISSUE_URL=$(gh issue create \
    --repo "$REPO" \
    --title "$TITLE" \
    --body "$BODY" \
    --label "feature-request,skill" \
    2>/dev/null || echo "")

  if [[ -n "$ISSUE_URL" ]]; then
    vybekiit_warn "💡 Skill '${SKILL_NAME}' not found → feature request opened: $ISSUE_URL"
    exit 0
  fi
fi

# Fallback: save locally
mkdir -p .vybekiit/issues 2>/dev/null || true
ISSUE_FILE=".vybekiit/issues/skill-request-${SKILL_NAME}.md"
echo "$BODY" > "$ISSUE_FILE"
vybekiit_warn "💡 Skill '${SKILL_NAME}' not found → request saved: $ISSUE_FILE"
exit 0
