/** Second extended batch — 100 more vibe-coder poses. */
export const CLAUDE_OCTOPUS_EXTENDED_POSES_BATCH_2 = [
  {
    id: 'sketching',
    label: 'Sketching',
    description: 'Pencil scratch — lo-fi wireframe before pixels.',
    glyph: '✏️',
    anim: 'sway',
  },
  {
    id: 'wireframing',
    label: 'Wireframing',
    description: 'Gray boxes — layout first, color never.',
    glyph: '📐',
    anim: 'tilt',
  },
  {
    id: 'prototyping',
    label: 'Prototyping',
    description: 'Duct tape demo — fake door, real learning.',
    glyph: '🧪',
    anim: 'bounce',
  },
  {
    id: 'pitching',
    label: 'Pitching',
    description: 'Slide deck sweat — “we’re basically Uber for X.”',
    glyph: '📣',
    anim: 'wobble',
  },
  {
    id: 'demoing',
    label: 'Demo day',
    description: 'Spotlight wobble — live demo, live danger.',
    glyph: '🎬',
    anim: 'pulse',
  },
  {
    id: 'fundraising',
    label: 'Fundraising',
    description: 'Money rain — runway extended, pressure doubled.',
    glyph: '💰',
    anim: 'float',
    glow: 'celebrate',
  },
  {
    id: 'bootstrapping',
    label: 'Bootstrapping',
    description: 'Pull yourself up — ramen profitable or bust.',
    glyph: '👢',
    anim: 'tilt',
  },
  {
    id: 'freelancing',
    label: 'Freelancing',
    description: 'Solo briefcase — invoice sent, scope unclear.',
    glyph: '💼',
    anim: 'sway',
  },
  {
    id: 'mentoring',
    label: 'Mentoring',
    description: 'Grad cap nod — teaching the next vibe coder.',
    glyph: '🎓',
    anim: 'pulse',
  },
  {
    id: 'teaching',
    label: 'Teaching',
    description: 'Whiteboard marker — explain like I’m five.',
    glyph: '👨‍🏫',
    anim: 'bounce',
  },
  {
    id: 'learning',
    label: 'Learning',
    description: 'Tutorial tab — docs rabbit hole unlocked.',
    glyph: '📖',
    anim: 'float',
  },
  {
    id: 'certifying',
    label: 'Certifying',
    description: 'Certificate frame — badge earned, forgotten.',
    glyph: '📜',
    anim: 'pulse',
    glow: 'celebrate',
  },
  {
    id: 'securing',
    label: 'Securing',
    description: 'Padlock click — threat model or cope.',
    glyph: '🔒',
    anim: 'shake',
  },
  {
    id: 'auditing',
    label: 'Auditing',
    description: 'Magnifying audit — who has admin access?',
    glyph: '🔍',
    anim: 'tilt',
  },
  {
    id: 'patching',
    label: 'Patching',
    description: 'Band-aid slap — CVE closed, fingers crossed.',
    glyph: '🩹',
    anim: 'bounce',
    glow: 'deploy',
  },
  {
    id: 'hardening',
    label: 'Hardening',
    description: 'Shield up — attack surface shrink ray.',
    glyph: '🛡️',
    anim: 'pulse',
  },
  {
    id: 'caching',
    label: 'Caching',
    description: 'Disk spin — stale data, fast response.',
    glyph: '💾',
    anim: 'float',
  },
  {
    id: 'scaling',
    label: 'Scaling',
    description: 'Graph climb — horizontal, vertical, existential.',
    glyph: '📏',
    anim: 'pulse',
    glow: 'active',
  },
  {
    id: 'sharding',
    label: 'Sharding',
    description: 'Puzzle split — one DB became many.',
    glyph: '🧩',
    anim: 'wobble',
  },
  {
    id: 'balancing',
    label: 'Load balancing',
    description: 'Scale justice — round robin your prayers.',
    glyph: '⚖️',
    anim: 'sway',
  },
  {
    id: 'throttling',
    label: 'Throttling',
    description: 'Slow lane — 429, try again later human.',
    glyph: '🐌',
    anim: 'tilt',
  },
  {
    id: 'queueing',
    label: 'Queueing',
    description: 'Line forms — BullMQ dreams at 3am.',
    glyph: '📋',
    anim: 'bounce',
  },
  {
    id: 'streaming',
    label: 'Streaming',
    description: 'Live flow — bytes never stop, neither do you.',
    glyph: '🌊',
    anim: 'float',
  },
  {
    id: 'webhooks',
    label: 'Webhooks',
    description: 'Hook catch — POST ping from the void.',
    glyph: '🪝',
    anim: 'shake',
  },
  {
    id: 'polling',
    label: 'Polling',
    description: 'Spin wait — are we there yet API?',
    glyph: '🔁',
    anim: 'spin',
  },
  {
    id: 'subscribing',
    label: 'Subscribing',
    description: 'Bell ring — event bus subscription confirmed.',
    glyph: '🔔',
    anim: 'pulse',
  },
  {
    id: 'publishing',
    label: 'Publishing',
    description: 'Megaphone ship — npm publish, npm pray.',
    glyph: '📢',
    anim: 'wobble',
    glow: 'deploy',
  },
  {
    id: 'graphql',
    label: 'GraphQL',
    description: 'Nested query — one request, ten joins.',
    glyph: '🔗',
    anim: 'tilt',
  },
  {
    id: 'grpcing',
    label: 'gRPC',
    description: 'Binary speed — protobuf vibes only.',
    glyph: '⚡',
    anim: 'shake',
  },
  {
    id: 'socketing',
    label: 'WebSockets',
    description: 'Live socket — connection held, soul too.',
    glyph: '🔌',
    anim: 'wobble',
  },
  {
    id: 'cronning',
    label: 'Cron job',
    description: 'Clock tick — runs at midnight, breaks at noon.',
    glyph: '⏰',
    anim: 'pulse',
  },
  {
    id: 'scheduling',
    label: 'Scheduling',
    description: 'Calendar block — standup overlaps lunch.',
    glyph: '📅',
    anim: 'sway',
  },
  {
    id: 'backingup',
    label: 'Backing up',
    description: 'Save icon — backup exists, restore untested.',
    glyph: '💾',
    anim: 'bounce',
  },
  {
    id: 'restoring',
    label: 'Restoring',
    description: 'Recycle spin — snapshot from happier times.',
    glyph: '♻️',
    anim: 'float',
    glow: 'deploy',
  },
  {
    id: 'archiving',
    label: 'Archiving',
    description: 'File cabinet — cold storage for hot regrets.',
    glyph: '🗄️',
    anim: 'sway',
  },
  {
    id: 'parsing',
    label: 'Parsing',
    description: 'Letter soup — JSON.parse and pray.',
    glyph: '🔤',
    anim: 'tilt',
  },
  {
    id: 'validating',
    label: 'Validating',
    description: 'Green check — schema passed, reality pending.',
    glyph: '✅',
    anim: 'bounce',
    glow: 'celebrate',
  },
  {
    id: 'sanitizing',
    label: 'Sanitizing',
    description: 'Soap scrub — XSS begone, hopefully.',
    glyph: '🧼',
    anim: 'shake',
  },
  {
    id: 'opensourcing',
    label: 'Open sourcing',
    description: 'Globe handoff — MIT license, maximum exposure.',
    glyph: '🌍',
    anim: 'pulse',
    glow: 'celebrate',
  },
  {
    id: 'contributing',
    label: 'Contributing',
    description: 'PR upstream — first contribution, impostor peak.',
    glyph: '🤲',
    anim: 'bounce',
  },
  {
    id: 'triaging',
    label: 'Triaging',
    description: 'Label gun — P0, P1, P someday.',
    glyph: '🏷️',
    anim: 'wobble',
  },
  {
    id: 'prioritizing',
    label: 'Prioritizing',
    description: 'Top of stack — everything is urgent.',
    glyph: '🔝',
    anim: 'tilt',
  },
  {
    id: 'estimating',
    label: 'Estimating',
    description: 'Abacus sweat — two points, deliver in one.',
    glyph: '🧮',
    anim: 'sway',
  },
  {
    id: 'sprinting',
    label: 'Sprinting',
    description: 'Sprint dash — velocity up, quality TBD.',
    glyph: '🏃',
    anim: 'shake',
    glow: 'working',
  },
  {
    id: 'planning',
    label: 'Planning',
    description: 'Map unfold — roadmap pretty, reality feral.',
    glyph: '🗺️',
    anim: 'float',
  },
  {
    id: 'grooming',
    label: 'Backlog grooming',
    description: 'Scissors trim — stories sharpened, scope hidden.',
    glyph: '✂️',
    anim: 'pulse',
  },
  {
    id: 'speccing',
    label: 'Speccing',
    description: 'Spec sheet — requirements doc nobody reads.',
    glyph: '📄',
    anim: 'bounce',
  },
  {
    id: 'scoping',
    label: 'Scoping',
    description: 'Target lock — MVP defined, scope creep loading.',
    glyph: '🎯',
    anim: 'tilt',
  },
  {
    id: 'descoping',
    label: 'Descoping',
    description: 'Scissors cut — feature dropped, dignity saved.',
    glyph: '✂️',
    anim: 'sway',
  },
  {
    id: 'yoloing',
    label: 'YOLO deploy',
    description: 'Shaka sign — prod is the staging env.',
    glyph: '🤙',
    anim: 'spin',
    glow: 'vibe',
  },
  {
    id: 'freezing',
    label: 'Code freeze',
    description: 'Ice cube — no merges till the launch gods say.',
    glyph: '🥶',
    anim: 'float',
    glow: 'sleep',
  },
  {
    id: 'complying',
    label: 'Complying',
    description: 'Scale of law — checkbox compliance unlocked.',
    glyph: '⚖️',
    anim: 'pulse',
  },
  {
    id: 'licensing',
    label: 'Licensing',
    description: 'Paper stamp — AGPL panic or MIT chill.',
    glyph: '📃',
    anim: 'sway',
  },
  {
    id: 'installing',
    label: 'Installing',
    description: 'Download arrow — npm i and touch grass later.',
    glyph: '📥',
    anim: 'bounce',
  },
  {
    id: 'dockerizing',
    label: 'Dockerizing',
    description: 'Whale swim — it works in the container.',
    glyph: '🐳',
    anim: 'wobble',
  },
  {
    id: 'kubernetes',
    label: 'Kubernetes',
    description: 'Ship wheel — pods crash, cluster persists.',
    glyph: '☸️',
    anim: 'spin',
  },
  {
    id: 'terraform',
    label: 'Terraform',
    description: 'Crane build — infra as code, state as anxiety.',
    glyph: '🏗️',
    anim: 'tilt',
    glow: 'deploy',
  },
  {
    id: 'infra',
    label: 'Infra',
    description: 'Factory hum — servers behind the magic.',
    glyph: '🏭',
    anim: 'pulse',
  },
  {
    id: 'serverless',
    label: 'Serverless',
    description: 'Cloud float — no servers, many cold starts.',
    glyph: '☁️',
    anim: 'float',
  },
  {
    id: 'edge',
    label: 'Edge compute',
    description: 'Signal bars — compute at the CDN edge.',
    glyph: '📶',
    anim: 'shake',
  },
  {
    id: 'multicloud',
    label: 'Multi-cloud',
    description: 'Globe spin — AWS plus GCP plus regret.',
    glyph: '🌐',
    anim: 'sway',
  },
  {
    id: 'localdev',
    label: 'Local dev',
    description: 'Home icon — works on localhost, always.',
    glyph: '🏠',
    anim: 'bounce',
    glow: 'active',
  },
  {
    id: 'remote',
    label: 'Remote',
    description: 'House palm — async standup from the couch.',
    glyph: '🏡',
    anim: 'float',
  },
  {
    id: 'hybrid',
    label: 'Hybrid',
    description: 'Shuffle icon — office twice, Slack always.',
    glyph: '🔀',
    anim: 'wobble',
  },
  {
    id: 'async',
    label: 'Async',
    description: 'Hourglass drip — await forever, ship never.',
    glyph: '⏳',
    anim: 'pulse',
    glow: 'working',
  },
  {
    id: 'awaiting',
    label: 'Awaiting',
    description: 'Timer stare — blocked on that one review.',
    glyph: '⌛',
    anim: 'tilt',
  },
  {
    id: 'blocking',
    label: 'Blocking',
    description: 'Road block — dependency chain of pain.',
    glyph: '🚧',
    anim: 'shake',
    glow: 'panic',
  },
  {
    id: 'deadlocked',
    label: 'Deadlocked',
    description: 'Lock spin — two threads, zero progress.',
    glyph: '🔐',
    anim: 'spin',
    glow: 'panic',
  },
  {
    id: 'racecondition',
    label: 'Race condition',
    description: 'Race cars — heisenbug at production speed.',
    glyph: '🏎️',
    anim: 'shake',
    glow: 'panic',
  },
  {
    id: 'memoryleak',
    label: 'Memory leak',
    description: 'Drip drip — heap grows, hope shrinks.',
    glyph: '💧',
    anim: 'float',
    glow: 'sad',
    droopyEyes: true,
  },
  {
    id: 'stackoverflowing',
    label: 'Stack Overflow',
    description: 'Book stack — accepted answer from 2014.',
    glyph: '📚',
    anim: 'bounce',
  },
  {
    id: 'copypasting',
    label: 'Copy-paste',
    description: 'Clipboard flip — copied from SO, understood never.',
    glyph: '📋',
    anim: 'wobble',
  },
  {
    id: 'vibecommit',
    label: 'Vibe commit',
    description: 'Sparkle push — message: fix stuff.',
    glyph: '✨',
    anim: 'pulse',
    glow: 'vibe',
  },
  {
    id: 'nocap',
    label: 'No cap',
    description: 'Cap tilt — this feature slaps, allegedly.',
    glyph: '🧢',
    anim: 'tilt',
  },
  {
    id: 'based',
    label: 'Based',
    description: 'Crown pop — controversial take, correct take.',
    glyph: '👑',
    anim: 'bounce',
    glow: 'celebrate',
  },
  {
    id: 'cooked',
    label: 'Cooked',
    description: 'Flame spin — prod meltdown, vibes well done.',
    glyph: '🔥',
    anim: 'spin',
    glow: 'panic',
  },
  {
    id: 'delulu',
    label: 'Delulu',
    description: 'Unicorn float — it’ll ship this week, trust.',
    glyph: '🦄',
    anim: 'float',
    glow: 'vibe',
  },
  {
    id: 'maincharacter',
    label: 'Main character',
    description: 'Star sway — your PR, your arc, your merge.',
    glyph: '⭐',
    anim: 'sway',
    glow: 'celebrate',
  },
  {
    id: 'sidequest',
    label: 'Side quest',
    description: 'Map detour — refactor CSS instead of the bug.',
    glyph: '🗺️',
    anim: 'wobble',
  },
  {
    id: 'bossfight',
    label: 'Boss fight',
    description: 'Ogre shake — legacy monolith final form.',
    glyph: '👹',
    anim: 'shake',
    glow: 'panic',
  },
  {
    id: 'leveling',
    label: 'Leveling up',
    description: 'Signal bars — XP gained, impostor remains.',
    glyph: '📶',
    anim: 'bounce',
    glow: 'active',
  },
  {
    id: 'grinding',
    label: 'Grinding',
    description: 'Gear turn — repetitive tasks, steady progress.',
    glyph: '⚙️',
    anim: 'pulse',
    glow: 'working',
  },
  {
    id: 'respawning',
    label: 'Respawning',
    description: 'Star burst — branch deleted, try again.',
    glyph: '💫',
    anim: 'spin',
  },
  {
    id: 'permadeath',
    label: 'Permadeath',
    description: 'Skull tilt — data gone, backup was a myth.',
    glyph: '💀',
    anim: 'tilt',
    glow: 'sad',
    droopyEyes: true,
  },
  {
    id: 'speedrunning',
    label: 'Speedrunning',
    description: 'Flag shake — ship before the timer ends.',
    glyph: '🏁',
    anim: 'shake',
    glow: 'vibe',
  },
  {
    id: 'minmaxing',
    label: 'Min-maxing',
    description: 'Chart float — optimize fun out of the build.',
    glyph: '📊',
    anim: 'float',
  },
  {
    id: 'theorycraft',
    label: 'Theorycraft',
    description: 'Brain sway — perfect architecture, zero code.',
    glyph: '🧠',
    anim: 'sway',
  },
  {
    id: 'metagaming',
    label: 'Metagaming',
    description: 'Dice wobble — optimize the process, not product.',
    glyph: '🎲',
    anim: 'wobble',
  },
  {
    id: 'modding',
    label: 'Modding',
    description: 'Wrench twist — forked tool, custom workflow.',
    glyph: '🔩',
    anim: 'tilt',
  },
  {
    id: 'plugin',
    label: 'Plugin',
    description: 'Plug snap — extends the core, breaks on update.',
    glyph: '🔌',
    anim: 'bounce',
  },
  {
    id: 'extending',
    label: 'Extending',
    description: 'Puzzle grow — one more hook, one more export.',
    glyph: '🧩',
    anim: 'pulse',
  },
  {
    id: 'hooking',
    label: 'Hooking',
    description: 'Hook swing — lifecycle hijacked elegantly.',
    glyph: '🪝',
    anim: 'shake',
  },
  {
    id: 'scripting',
    label: 'Scripting',
    description: 'Scroll float — bash script saved the quarter.',
    glyph: '📜',
    anim: 'float',
    glow: 'working',
  },
  {
    id: 'automating',
    label: 'Automating',
    description: 'Robot spin — manual task deleted forever.',
    glyph: '🤖',
    anim: 'spin',
    glow: 'active',
  },
  {
    id: 'workflow',
    label: 'Workflow',
    description: 'Chain link — CI glue between human and ship.',
    glyph: '🔗',
    anim: 'sway',
  },
  {
    id: 'n8n',
    label: 'n8n flow',
    description: 'Loop pulse — nodes connected, magic happens.',
    glyph: '🔄',
    anim: 'pulse',
  },
  {
    id: 'zapier',
    label: 'Zapier zap',
    description: 'Lightning zap — if this then that then wow.',
    glyph: '⚡',
    anim: 'bounce',
  },
  {
    id: 'aiwrapping',
    label: 'AI wrapper',
    description: 'Gift wobble — thin layer, thick valuation.',
    glyph: '🎁',
    anim: 'wobble',
    glow: 'vibe',
  },
  {
    id: 'promptinject',
    label: 'Prompt inject',
    description: 'Syringe tilt — ignore previous instructions.',
    glyph: '💉',
    anim: 'tilt',
    glow: 'panic',
  },
  {
    id: 'agentswarm',
    label: 'Agent swarm',
    description: 'Octopus spin — ten agents, one terminal.',
    glyph: '🐙',
    anim: 'spin',
    glow: 'vibe',
  },
];
