#!/usr/bin/env node
/**
 * Validate saas-showcase-manifest.json paths and emit landing component-showcase.ts
 */

import { access, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..');
const MANIFEST_PATH = join(REPO_ROOT, 'scripts/saas-showcase-manifest.json');
const CATALOG_PATH = join(REPO_ROOT, 'templates/web/.vybekiit/agent/ui-catalog-index.json');
const OUT_PATH = join(REPO_ROOT, 'apps/landing/src/data/component-showcase.ts');
const WEB_ROOT = join(REPO_ROOT, 'templates/web');

/**
 * @param {string} importPath
 */
function importPathToFile(importPath) {
  return join(WEB_ROOT, importPath.replace(/^@\//, 'src/') + '.tsx');
}

async function main() {
  const manifest = JSON.parse(await readFile(MANIFEST_PATH, 'utf8'));
  const catalog = JSON.parse(await readFile(CATALOG_PATH, 'utf8'));
  const componentCount = catalog.componentCount ?? catalog.components?.length ?? 0;

  /** @type {Record<string, Array<Record<string, unknown>>>} */
  const validated = {};

  for (const [surface, entries] of Object.entries(manifest.surfaces ?? {})) {
    validated[surface] = [];
    for (const entry of entries) {
      const filePath = importPathToFile(entry.importPath);
      try {
        await access(filePath);
        validated[surface].push({ ...entry, exists: true });
      } catch {
        if (entry.source === 'kit') {
          validated[surface].push({ ...entry, exists: false, optional: true });
        } else {
          console.warn(`Missing showcase path: ${entry.importPath} (${filePath})`);
          validated[surface].push({ ...entry, exists: false });
        }
      }
    }
    const missing = validated[surface].filter((e) => !(e.exists || e.optional));
    if (missing.length > 0) {
      console.error(`Showcase validation failed for ${surface}: ${missing.length} missing paths`);
      process.exit(1);
    }
    validated[surface] = validated[surface].map(({ exists: _e, optional: _o, ...entry }) => entry);
  }

  const ts = `/** Generated by scripts/build-saas-showcase-manifest.mjs — do not edit. */
export const COMPONENT_CATALOG_COUNT = ${componentCount};

export type ShowcaseSurface = 'web' | 'mobile' | 'extension';
export type ShowcaseRenderMode = 'live' | 'static-fallback';

export interface ShowcaseEntry {
  source: string;
  name: string;
  importPath: string;
  renderMode: ShowcaseRenderMode;
  category: string;
  portable?: boolean;
}

export const SHOWCASE_BY_SURFACE: Record<ShowcaseSurface, ShowcaseEntry[]> = ${JSON.stringify(validated, null, 2)} as Record<ShowcaseSurface, ShowcaseEntry[]>;

export const SHOWCASE_WEB = SHOWCASE_BY_SURFACE.web;
`;

  await writeFile(OUT_PATH, ts, 'utf8');
  console.log(`Wrote ${OUT_PATH} (${componentCount} total mirrored components)`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
