/** Generated by scripts/dev/sync/buildComponentLibraryIndex.mjs — do not edit. */
export type {
  CatalogCategory,
  CatalogEntry,
  CatalogKind,
  DemoSource,
  RenderMode,
  UnavailableReason,
} from './catalog';

export const COMPONENT_CATALOG_COUNT = 1874;
export const CATALOG_COMPONENT_COUNT = 1537;
export const CATALOG_EXAMPLE_COUNT = 337;

export const CATALOG_CATEGORIES = [
  {
    slug: 'brand-mascots',
    label: 'VybeKiit mascots',
    count: 215,
    order: 0,
  },
  {
    slug: 'hero',
    label: 'Hero & landing',
    count: 187,
    order: 1,
  },
  {
    slug: 'background',
    label: 'Backgrounds & effects',
    count: 129,
    order: 2,
  },
  {
    slug: 'navigation',
    label: 'Navigation',
    count: 68,
    order: 3,
  },
  {
    slug: 'form',
    label: 'Forms & inputs',
    count: 412,
    order: 4,
  },
  {
    slug: 'button',
    label: 'Buttons & actions',
    count: 131,
    order: 5,
  },
  {
    slug: 'card',
    label: 'Cards & content',
    count: 148,
    order: 6,
  },
  {
    slug: 'data-display',
    label: 'Data display',
    count: 209,
    order: 7,
  },
  {
    slug: 'ai',
    label: 'AI & chat',
    count: 219,
    order: 8,
  },
  {
    slug: 'icons-logos',
    label: 'Logos & icons',
    count: 18,
    order: 9,
  },
  {
    slug: 'pricing',
    label: 'Pricing & marketing',
    count: 55,
    order: 10,
  },
  {
    slug: 'layout',
    label: 'Layout & shells',
    count: 40,
    order: 11,
  },
  {
    slug: 'base',
    label: 'Primitives',
    count: 9,
    order: 12,
  },
  {
    slug: 'application',
    label: 'Application',
    count: 1,
    order: 13,
  },
  {
    slug: 'component',
    label: 'Other',
    count: 33,
    order: 99,
  },
] as import('./catalog').CatalogCategory[];

export const CATALOG_NAMESPACES: readonly string[] = [
  'aceternity',
  'ai-elements',
  'blocks-so',
  'bundui',
  'coss',
  'cult',
  'evilcharts',
  'kibo',
  'kokonutui',
  'magicui',
  'prompt-kit',
  'supabase',
  'tailark',
  'vybekiit',
] as const;
