/** Generated by scripts/dev/sync/buildComponentLibraryIndex.mjs — do not edit. */

export const COMPONENT_CATALOG_COUNT = 2126;
export const CATALOG_COMPONENT_COUNT = 1789;
export const CATALOG_EXAMPLE_COUNT = 337;

export const CATALOG_CATEGORIES = [
  {
    "slug": "brand-mascots",
    "label": "VybeKiit mascots",
    "count": 215,
    "order": 0
  },
  {
    "slug": "hero",
    "label": "Hero & landing",
    "count": 198,
    "order": 1
  },
  {
    "slug": "background",
    "label": "Backgrounds & effects",
    "count": 139,
    "order": 2
  },
  {
    "slug": "navigation",
    "label": "Navigation",
    "count": 72,
    "order": 3
  },
  {
    "slug": "form",
    "label": "Forms & inputs",
    "count": 421,
    "order": 4
  },
  {
    "slug": "button",
    "label": "Buttons & actions",
    "count": 141,
    "order": 5
  },
  {
    "slug": "card",
    "label": "Cards & content",
    "count": 153,
    "order": 6
  },
  {
    "slug": "data-display",
    "label": "Data display",
    "count": 234,
    "order": 7
  },
  {
    "slug": "ai",
    "label": "AI & chat",
    "count": 219,
    "order": 8
  },
  {
    "slug": "icons-logos",
    "label": "Logos & icons",
    "count": 38,
    "order": 9
  },
  {
    "slug": "pricing",
    "label": "Pricing & marketing",
    "count": 136,
    "order": 10
  },
  {
    "slug": "layout",
    "label": "Layout & shells",
    "count": 49,
    "order": 11
  },
  {
    "slug": "base",
    "label": "Primitives",
    "count": 65,
    "order": 12
  },
  {
    "slug": "application",
    "label": "Application",
    "count": 9,
    "order": 13
  },
  {
    "slug": "component",
    "label": "Other",
    "count": 37,
    "order": 99
  }
] as import('./catalog').CatalogCategory[];

export const CATALOG_NAMESPACES: readonly string[] = ["aceternity","ai-elements","blocks-21st","blocks-so","bundui","coss","cult","evilcharts","gluestack","kibo","kokonutui","magicui","prompt-kit","supabase","tailark","untitled","vybekiit"] as const;
