/** Generated by scripts/dev/changelog/generateChangelog.mjs - do not edit (ADR-0041). */
// biome-ignore-all format: generated changelog data stays byte-stable for check mode.
export interface ChangelogCommit {
  readonly type: string;
  readonly section: string;
  readonly scope: string | null;
  readonly description: string;
  readonly pr: number | null;
  readonly breaking: boolean;
}

export interface ChangelogRelease {
  readonly version: string;
  readonly date: string | null;
  readonly commits: readonly ChangelogCommit[];
}

export interface RoadmapItem {
  readonly number: number;
  readonly title: string;
  readonly stage: string;
  readonly mark: string;
  readonly state: string;
  readonly url: string;
}

export interface ChangelogData {
  readonly legend: Readonly<Record<string, string>>;
  readonly releases: readonly ChangelogRelease[];
  readonly roadmap: readonly RoadmapItem[];
}

export const CHANGELOG_DATA = {
  "legend": {
    "✅": "Shipped + confirmed working",
    "🔄": "In progress this iteration",
    "⬜": "Not started",
    "🅿️": "Parked (code/unit done; live blocked on external login)",
    "🧪": "Needs network / secrets (gated)",
    "💻": "Pure code, no secrets"
  },
  "releases": [
    {
      "version": "Unreleased",
      "date": null,
      "commits": [
        {
          "type": "fix",
          "scope": "browserAutomation",
          "description": "idempotent Google OAuth URI patch from anywhere",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "release",
          "description": "cap turbo concurrency to avoid runner OOM cancel",
          "pr": 80,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "first-run kit workspace + release bump for nested packages",
          "pr": 79,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "hover language switcher + EN/HE/RU/AR visitor copy",
          "pr": 78,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "fix",
          "scope": "scripts",
          "description": "force-track checkPageRecipes.mjs gate entrypoint",
          "pr": 77,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "restore multilang READMEs, recipe rebuilds, and local fixes",
          "pr": 76,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "pricing polish, perf shells, built-with note",
          "pr": 75,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "recipes",
          "description": "make PricingPage a production-ready recipe",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "recipes",
          "description": "make AuthPage a production-ready recipe",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "componentLibrary",
          "description": "production-ready Checkout page recipe + authoring bar",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": "landing",
          "description": "flip LEMONSQUEEZY_TEST_MODE to false (go live)",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "landing",
          "description": "gate sends User-Agent + serial invites; wire D1 binding",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "payments",
          "description": "LS webhook admin module + ls:webhooks CLI",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "ignore .wrangler/state recursively (nested apps use D1)",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "record orders in Cloudflare D1 (one orders table)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "browser-automation",
          "description": "generic money-pipeline verification (ls verify-checkout)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "fix",
          "scope": "browser-automation",
          "description": "mint CF tokens at the account-scoped URL",
          "pr": 66,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "ci",
          "description": "componentLibrary build tolerates a missing sync:ui catalog",
          "pr": 63,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "SEO — robots, sitemap, OG image, JSON-LD, full metadata",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "fix",
          "scope": "ci",
          "description": "green typecheck/test — pageRecipe casing + walkthrough module",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "d1-d8",
          "description": "resync brand assets to SSOT + finish web cnfast migration",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": "d1-d8",
          "description": "commit in-flight hardening WIP before main merge",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "landing",
          "description": "resolve TS7030 in a biome-stable way",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "refactor",
          "scope": "spa",
          "description": "convert first-party default exports to named exports",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "spa",
          "description": "convert parent-relative imports to the @/ alias",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "landing",
          "description": "PascalCase the first-party component files",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "reportMode",
          "description": "camelCase the use-*.ts hook files",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "tests",
          "description": "colocate all 103 package tests beside their subjects",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "docs",
          "scope": "code-style",
          "description": "close CODE-STYLE gaps + wire lint enforcement",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "checkpoint D1-D8 hardening work",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "specify page recipe catalog",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "preflight scripts + competitive-features doc",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "agent-kit",
          "description": "hooks, MCP, and platform adapters",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "ui",
          "description": "private @vybekiit/ui component library package",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "dedup",
          "description": "Rust duplicate-export gate tool (ADR-0031)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "style",
          "scope": null,
          "description": "regex example comments + durable UI-registry sync transform",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "browser-automation",
          "description": "provider token/key automation + toolchain (ADR-0032)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": "dist",
          "description": "publish CLI only, privatize all @vybekiit/* packages (ADR-0033)",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "gate",
          "scope": null,
          "description": "wire e2e into pnpm verify + update AGENTS.md docs",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "e2e",
          "scope": null,
          "description": "add Playwright tests for local-dev (agent-switch, session-load, workflow-real) + mock daemon",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "e2e",
          "scope": null,
          "description": "Playwright tests for local-dev agent switch, session load, workflow real",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "browser-automation: Supabase + Cloudflare stubs with .env key guard",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "local-dev: new localDevelopmentWebsite with real workflows and multi-agent sessions",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "meta",
          "scope": null,
          "description": "update docs, husky hook, landing tsconfig",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "landing",
          "scope": null,
          "description": "update sections and styles",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "cleanup",
          "scope": null,
          "description": "remove dead fixture, guard junk dirs in .gitignore",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "templates/web",
          "description": "add agent runtime configs, CI hardening, catalog refresh and skill updates",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates/spa",
          "description": "add agent runtime configs, CI and gitignore hardening",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates/mobile",
          "description": "add agent runtime configs, CI hardening and skill updates",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates/extension",
          "description": "add agent runtime configs, CI hardening and skill updates",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates/backend",
          "description": "add agent runtime configs and railway skill updates",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "refresh landing styles, add AI tool brand marks and wrangler state",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agentKit",
          "description": "expand supported agent runtimes and tool skill paths",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "add tsup workspace alias declarations and biome backup",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "update agent contract and code-style rules",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "document scripts/dev/ convention (gitignored)",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "hardening",
          "description": "D1-D8 hardening",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "browser-automation",
          "description": "complete the Google OAuth consent flow",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "browser-automation",
          "description": "one-shot Google OAuth setup domain",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "deploy to Cloudflare via OpenNext + partner referral SSOT",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "style",
          "scope": null,
          "description": "apply biome formatting (line-wrap collapse, type-only import markers)",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "refactor",
          "scope": "email+notifications",
          "description": "fold into web as owned code (ADR-0025) + Effect schema migration",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "assets",
          "description": "fold @vybekiit/assets into web + mobile + extension (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "fix",
          "scope": "analytics",
          "description": "read web env via nodeEnv shim so biome stops re-adding node:process",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "refactor",
          "scope": "analytics",
          "description": "fold @vybekiit/analytics into web + backend (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "realtime",
          "description": "fold @vybekiit/realtime into web + spa as owned code (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "i18n",
          "description": "fold the pure locale-rules surface into mobile + spa (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "concerns",
          "description": "fold 7 web-only leaf concerns into the web template (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "seo",
          "description": "fold @vybekiit/seo into the web template as owned code (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "auth",
          "description": "absorb Twilio SMS-OTP from notifications; sever auth→notifications (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "core",
          "description": "absorb http/observability/security as subpaths (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "packages",
          "description": "privatize agent-kit + browser-automation; bundle into CLI (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "packages",
          "description": "privatize deploy + ui-catalog-mcp (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "chore",
          "scope": "templates",
          "description": "pin regenerated use-railway skill + format landing components",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "refactor",
          "scope": "landing",
          "description": "restyle landing components; sync CI workflows and templates",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "collapse published surface to 5 + split structure docs (ADR-0025)",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "ci",
          "description": "install Chromium in the test leg for browser-automation's field-locator suite",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "sync pinned platform skills (posthog + feature-flags + eas-simulator)",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "mirror",
          "description": "drop unmade spa/backend targets, reconcile to ADR-0005's five delivery repos",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "sync pinned platform skills (mongodb refresh + web-to-native)",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "ignore .pi/ skills-CLI cache directory",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "hooks",
          "description": "repair pre-push pin-skills path broken by the camelCase rename",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "ci",
          "description": "scope checks leg to cold-safe checks; keep check:templates pre-push",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "landing",
          "description": "drop non-hermetic brand-mark generation from build",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "templates/web",
          "description": "declare cmdk, embla-carousel-react, react-day-picker",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "ci",
          "description": "activate pnpm via corepack in gate legs for act compatibility",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "remaining root config + camelCase stragglers",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": "scripts",
          "description": "remove stale image-gen scripts; camelCase; regex comments",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "ci",
          "scope": null,
          "description": "decompose gate into act-runnable reusable legs + CI Gate; add .actrc",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "component-library",
          "description": "honest catalog + light/dark + global color picker",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "refactor",
          "scope": "landing",
          "description": "camelCase renames + Effect consumers",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "cli",
          "description": "Effect + camelCase file renames",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "templates",
          "description": "Effect consumers + camelCase + edge-runtime build fixes",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "packages",
          "description": "migrate to Effect (tagged errors, Schema, Layers) + camelCase folders/files",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "chore",
          "scope": "deps",
          "description": "add effect + @effect/vitest, drop zod, vitest 2->3; sync lockfile",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "adopt Effect end-to-end (ADR-0023); camelCase files + regex rule in CODE-STYLE/AGENTS",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "format component library catalog for biome pre-push lint.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "sync pinned platform skill stubs and skills-lock after quality gate.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Regenerate component library catalog index after UI registry expansion.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Register add-realtime goal in catalog and sync web buyer skill stubs.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Update mirror-repos tests for SPA and backend delivery mirrors.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Update extension i18n test for underscore Chrome message key names.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Fix SPA rich text editor Tiptap extension typing for pre-push typecheck.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Scope component-library typecheck to catalog shell and sync lockfile for Radix deps.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Exclude mirrored registry namespaces from web typecheck and add missing Radix UI deps.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Fix browser-automation typecheck for Chrome launch API and registrar env parsing.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Fix payments HTTP test typing for practice completion response body.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Pass test mode and enabled variant options into Lemon Squeezy checkout creation.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "sync workspace manifests, env example, and lockfile for round-3 features.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add component library app with landing showcase and Pages deploy workflow.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Update web checkout fulfillment, practice mode, and buyer goal skills.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Wire SPA checkout page and align mobile and backend template dependencies.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Ship extension sidepanel scaffold with auth shell and billing wire points.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Expand web template with mirrored registry blocks, shadcn primitives, and demos.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Expand UI registry sync, catalog index builder, and agent vocabulary.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add Supabase order migration, RLS policies, and domain provision script.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add CLI presets command and doctor verify steps for email, registrars, and DB.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Extend better-auth tenancy provider for preset user profile bridge.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add registrar credential onboarding via browser-automation (ADR-0021).",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Improve Lemon Squeezy dashboard auth flow and variant verification.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Harden browser-automation core with Chrome launch, profile resolve, and redirect waits.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add registrar API clients and Cloudflare zone helpers to deploy package.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add Cloudflare email worker contract and provider integration.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add relational DB feature presets with Postgres-first provider support.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Replace http-client with @vybekiit/http and wire auth, payments, and security handlers.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add Node env loader and expand core config resolution.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Fix createAuthClient test typing for generic postJson mock.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "update lockfile for round-2 template and package dependencies.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add backend checkout and webhook pipeline with shared payment handlers.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Adopt http-client and query persistence in the extension template.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add SPA auth and billing wire points with SignInForm integration.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Wire mobile auth-client through createAuthClient with MSW tests.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Collapse web provider registry and wire security plus persistence.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add Express security middleware adapter.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add shared payment HTTP handlers and practice-mode helper.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add createAuthClient factory for template auth wire points.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Fall back unshipped provider adapters to local implementations.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Deepen auth session seam and collapse duplicated HTTP handlers.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": "mobile",
          "description": "sync platform skills lock after architecture refactor",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "keep instrumentation.ts out of biome node:process injection",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "web",
          "description": "read process via globalThis seam and exclude instrumentation from biome",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "i18n",
          "description": "add browser-safe locale-rules subpath for SPA and mobile",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "web",
          "description": "avoid explicit node:process imports that break client bundle",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "satisfy typecheck on optional reads and landing demo effects",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "browser-automation",
          "description": "restore optional text return on field read failure",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "cli",
          "description": "satisfy typecheck in optional file and live-docs parsers",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "cli",
          "description": "restore explicit undefined returns for typecheck after biome format",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "refactor",
          "scope": null,
          "description": "deepen CLI and maintained packages from architecture review",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "chore",
          "scope": "templates",
          "description": "pin use-railway skill and sync onboarding stubs",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "templates",
          "description": "sync backend onboarding skill stub after render",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "landing",
          "description": "satisfy useEffect return type in agent session demo",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "clarify bridge login requires quitting daily Chrome",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "web",
          "description": "remove explicit node:process imports breaking Next build",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "landing",
          "description": "emit biome-formatted brand-marks manifest from generator",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "web",
          "description": "remove node:process import breaking client bundle",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": "landing",
          "description": "format brand-marks-3d catalog",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "cli",
          "description": "restore returns in empty catch blocks after biome format",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "browser-automation",
          "description": "restore return in readOptionalText catch path",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "resolve nested ternary biome errors blocking quality gate",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "apply biome formatting across maintained packages",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "cli",
          "description": "add setup command and welcome banner",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "add Hero product stack orbit with 3D brand marks",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "add ADRs, update maintainer guides, and checklist scaffold",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": "templates",
          "description": "sync agent layer, skills, and platform pins",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": "scripts",
          "description": "add platform skills and agent layer CI gates",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "cli",
          "description": "add agent layer render/sync and skill discovery",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "cli",
          "description": "extend doctor for Railway, Codex skills, and dispatch",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agent-kit",
          "description": "add buyer skill stubs and extension skill lint",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agent-kit",
          "description": "add platform skills audit and manifest merge",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "refactor",
          "scope": "agent-kit",
          "description": "clean module layout and expand vocabulary",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "refactor",
          "scope": "packages",
          "description": "migrate resolve.ts to core dispatch",
          "pr": null,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "feat",
          "scope": "db,deploy",
          "description": "add Railway stack adapters (ADR-0017)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "core",
          "description": "add provider dispatch SSOT (ADR-0018)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Gate agent wiring with agnix and runtime compliance checks.",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "sync tech-references from platform skills pin",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "sync platform skills pin output",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "mirror",
          "description": "skip spa delivery mirror until VybeKiit/spa repo exists",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "sync CONTEXT after pin-platform-skills",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "web",
          "description": "drop unused shadcn primitives that broke strict template build",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "web",
          "description": "satisfy biome a11y on breadcrumb and input-otp primitives",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "ci",
          "scope": null,
          "description": "defer spa template agent-layer gate until skills are synced",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "gate",
          "description": "include spa mirror in default GitHub gate repos",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "ci",
          "scope": null,
          "description": "defer spa template agent-layer gate until skills are synced",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "test",
          "scope": null,
          "description": "expect spa mirror in default delivery mirror set",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "drop legacy web routes superseded by [locale] layout",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "remove duplicate CLI modules and WIP backend realtime stub",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "remove orphan socket-io realtime test",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "restore CI after branch merges — spa catalog entries, drop WIP realtime stubs, exclude spa assets from lint",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "resolve merge-duplicate declarations from branch integration",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Co-authored-by: Cursor <cursoragent@cursor.com>",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "web",
          "description": "resolve landing grid and auth-telemetry test type errors",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "agent-layer",
          "description": "enforce patterns, PostHog/Sentry wave, and landing hints",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "add vibe hints on brand marks with hero domino cascade",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "flat brand mark WebPs and remove 3d asset pipeline",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates",
          "description": "MCP tier for Supabase, Stripe, and PayPal",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates",
          "description": "wire browser-automation skills and buyer store scaffolds",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": "browser-automation",
          "description": "apply formatter output from pre-commit hook",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "wire monorepo for browser-automation SSOT",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "remove extension-publish package",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "browser-automation",
          "description": "add unified CWS and Lemon Squeezy automation package",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "update CONTEXT and env example for client-state policy",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": "skills",
          "description": "align save-data and react patterns for MCP-tier providers",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": "skills",
          "description": "add client-state, data-model, and browser-automation guides",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": "web",
          "description": "document client-state hooks and theme token usage",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "extension",
          "description": "wire client-state provider in popup entrypoint",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "mobile",
          "description": "wire client-state with MMKV query persist",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": "scripts",
          "description": "register client-state and browser-automation packages",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "cli",
          "description": "omit Supabase CLI for MCP-first data providers",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "docs",
          "scope": "client-state",
          "description": "add package README and CONTEXT glossary",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": "kv",
          "description": "clarify agent-only scope and no Redis buyer path",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "agent-kit",
          "description": "emit FK columns for all relation types in SQL migrations",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "db",
          "description": "export neon and firebase adapters from package entry",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "docs",
          "scope": "adr",
          "description": "add client-state and browser-automation decisions",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "npm first publish OTP runbook",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "format asset manifests",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "release",
          "description": "production readiness — CI fix, release/publish workflows, landing polish",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "fix",
          "scope": "hooks",
          "description": "pre-push gate skips mirror remotes; mirror CI's test:scripts",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "dist",
          "description": "mirror all five delivery repos, populate-ready (ADR-0005)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "inspirations gallery (#35) + Terminal-to-Live hero",
          "pr": 36,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "apply biome format and lint fixes",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "cli",
          "description": "satisfy typecheck in sync-agent-layer test mock",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "marketing site scaffold and workspace promotion",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "ADR-0007, CONTEXT skills inventory, and positioning research",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "templates/extension",
          "description": "v3 agent layer and skills bridge",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates/mobile",
          "description": "skills bridge buyer layer parity",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates/web",
          "description": "skills bridge buyer layer and language parity",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "cli",
          "description": "sync-agent-layer command for update-kit channel 2",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agent-kit",
          "description": "agent-layer sync and platform skills planners",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates",
          "description": "Layer B platform wrapper skills",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates/mobile",
          "description": "pin expo agent skills suite",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates/web",
          "description": "pin vercel-labs agent skills",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "templates",
          "description": "platform skills manifest, pin script, and CI step",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "align save-data skill naming in code and onboarding copy",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "deploy",
          "description": "add Vercel hosting adapter as opt-in provider",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "ignore local artifacts and pinned agent skills in Biome",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "ci",
          "description": "one-way template mirror sync (script + workflow)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "cli",
          "description": "clone the private mirror to scaffold; add gh to doctor",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agent-kit",
          "description": "shared agent-layer package + Cursor support + tool-vocabulary",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "mobile",
          "description": "buyer agent layer + skills + Expo/EAS/launch doctor tools (#19, #15)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "mobile",
          "description": "Expo template at web parity — StyleSheet primitives + screens + launch config",
          "pr": 19,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "web",
          "description": "reusable hooks + fetch helper + toast + test setup",
          "pr": 16,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agent",
          "description": "six goal-named skills + provider-aware doctor + data maps (#14/#15)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "auth",
          "description": "AuthProvider interface — better-auth (DB-bound) + Cognito (AWS) — ADR-0003",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "aws",
          "description": "hosting (Amplify) + storage (S3) + email (SES) adapters; fix web typecheck ordering",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "db",
          "description": "MongoDB (Atlas) + AWS (DynamoDB) data adapters behind DataProvider",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "packages",
          "description": "provider-interface seams (data/storage/hosting/email) + @vybekiit/tokens",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "record multi-provider adapter widening (ADR-0002/0003/0004) + expand language.md",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "web",
          "description": "scaffold-ready buyer page layouts on a shadcn foundation",
          "pr": null,
          "breaking": false,
          "section": "Added"
        }
      ]
    },
    {
      "version": "0.3.0",
      "date": "2026-06-30",
      "commits": [
        {
          "type": "fix",
          "scope": "client-state",
          "description": "annotate MMKV persister return type for dts build",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": "mobile",
          "description": "format root layout for biome gate",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "format client-state package and fix landing effect cleanups",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "sync platform skills and optimized assets after rebase",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "landing",
          "description": "use no-op effect cleanup for strict TypeScript builds",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": "mobile",
          "description": "sync optimized asset outputs from build pipeline",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "assets",
          "description": "write trailing newline in asset-manifest.json",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "extension",
          "description": "resolve wxt/utils/storage for workspace report-mode",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "landing",
          "description": "satisfy strict useEffect and chart payload types",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "fix",
          "scope": "extension",
          "description": "use outline variant for highlight reset button",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "add inspect highlight glossary term to CONTEXT",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": "release",
          "description": "v0.3.0 — pin platform skills and bump kit semver",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "update CONTEXT, AGENTS, env example, and maintainer guides",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "templates",
          "description": "web lib hardening and shared UI primitives",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "cinematic landing with showcase carousel and brand marks",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "report-mode",
          "description": "dock, inspect, handoff, and tutorial improvements",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agent",
          "description": "platform skills and MCP for Neon, Firebase, and AWS",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "packages",
          "description": "add ui-catalog-mcp server for agent component discovery",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "ui",
          "description": "registry sync pipeline and mirrored component catalog",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": "lint",
          "description": "relax biome rules for UI mirrors and report-mode",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": "release",
          "description": "pin platform skills for v0.1.1",
          "pr": null,
          "breaking": false,
          "section": "Other"
        }
      ]
    },
    {
      "version": "0.1.1",
      "date": "2026-06-29",
      "commits": [
        {
          "type": "chore",
          "scope": "release",
          "description": "v0.1.1",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "release",
          "description": "unblock npm publish when mirror sync fails",
          "pr": 48,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": "release",
          "description": "pin platform skills for v0.1.0",
          "pr": null,
          "breaking": false,
          "section": "Other"
        }
      ]
    },
    {
      "version": "0.1.0",
      "date": "2026-06-29",
      "commits": [
        {
          "type": "fix",
          "scope": "release",
          "description": "skip husky pre-push on CI bot pushes.",
          "pr": 47,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "other",
          "scope": null,
          "description": "Add npm READMEs for all @vybekiit/* packages.",
          "pr": 46,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "release",
          "description": "production readiness — CI, release workflows, landing polish",
          "pr": 45,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "sync extension asset manifest after optimize-assets",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": "report-mode",
          "description": "avoid WXT storage auto-import collision",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "Report Mode glossary, buyer voice, and skill updates",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "update lockfile for report-mode workspace dependencies",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "extension",
          "description": "wire dev Report Mode in popup with dock and handoff",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "mobile",
          "description": "wire dev Report Mode with dock and modal handoff",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "web",
          "description": "wire dev Report Mode shell, dock, and assistant handoff",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "cli",
          "description": "surface Report Mode assistant hints in doctor",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agent-kit",
          "description": "add Report Mode UI vocabulary",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "report-mode",
          "description": "complete @vybekiit/report-mode package",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "format extension asset-manifest.json",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "fix",
          "scope": null,
          "description": "gate green on report-mode deeplink test and biome format",
          "pr": null,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "pin platform skills after GEO template sync",
          "pr": null,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "seo",
          "description": "extend @vybekiit/seo with GEO primitives and wire web template",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "security",
          "description": "secure-by-default vertical + delivery READMEs (ADR-0009)",
          "pr": null,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "fix",
          "scope": "hooks",
          "description": "pre-push gate skips mirror remotes; mirror CI's test:scripts",
          "pr": 43,
          "breaking": false,
          "section": "Fixed"
        },
        {
          "type": "feat",
          "scope": "dist",
          "description": "mirror all five delivery repos, populate-ready (ADR-0005)",
          "pr": 42,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "landing",
          "description": "inspirations gallery (#35) + Terminal-to-Live hero (#36)",
          "pr": 41,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "db,auth",
          "description": "local dev adapter — fresh scaffold runs with no secrets (ADR-0008)",
          "pr": 40,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "docs",
          "scope": "voice,license",
          "description": "expand buyer glossary (4 clusters) + finalize LICENSE/EULA split (#18)",
          "pr": 39,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": null,
          "description": "landing page + platform skills + agent-layer sync (#3)",
          "pr": 34,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "ci",
          "description": "one-way template mirror sync (script + workflow)",
          "pr": 33,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "cli",
          "description": "clone the private mirror to scaffold; add gh to doctor",
          "pr": 32,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agent-kit",
          "description": "shared agent-layer package + Cursor support + tool-vocabulary",
          "pr": 31,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "mobile",
          "description": "buyer agent layer + skills + Expo/EAS/launch doctor tools (#19, #15)",
          "pr": 30,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "mobile",
          "description": "Expo template at web parity — StyleSheet primitives + screens + launch config (#19)",
          "pr": 29,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "web",
          "description": "reusable hooks + fetch helper + toast + test setup (#16)",
          "pr": 28,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "agent",
          "description": "six goal-named skills + provider-aware doctor + data maps (#14/#15)",
          "pr": 27,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "auth",
          "description": "AuthProvider interface — better-auth (DB-bound) + Cognito (AWS) — ADR-0003",
          "pr": 26,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "aws",
          "description": "hosting (Amplify) + storage (S3) + email (SES) adapters; fix web typecheck ordering",
          "pr": 25,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "db",
          "description": "MongoDB (Atlas) + AWS (DynamoDB) data adapters behind DataProvider",
          "pr": 24,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "packages",
          "description": "provider-interface seams (data/storage/hosting/email) + @vybekiit/tokens",
          "pr": 23,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "docs",
          "scope": null,
          "description": "record multi-provider adapter widening (ADR-0002/0003/0004) + expand language.md",
          "pr": 22,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "feat",
          "scope": "web",
          "description": "scaffold-ready buyer page layouts on a shadcn foundation",
          "pr": 21,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "web",
          "description": "promote templates/web to a workspace member + CI gate (#2)",
          "pr": 12,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "feat",
          "scope": "cli",
          "description": "add `vybekiit doctor` — provision + verify the agentic toolchain",
          "pr": 11,
          "breaking": false,
          "section": "Added"
        },
        {
          "type": "refactor",
          "scope": null,
          "description": "rename @vybekiit/browser-automation → @vybekiit/extension-publish",
          "pr": 10,
          "breaking": false,
          "section": "Changed"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "harden gate (pre-push mirrors CI, max-strict TS) + capture grill decisions",
          "pr": 9,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "structural",
          "scope": null,
          "description": "provider-agnostic payments + @vybekiit/browser-automation + CI badge",
          "pr": 1,
          "breaking": false,
          "section": "Other"
        },
        {
          "type": "chore",
          "scope": null,
          "description": "scaffold VybeKiit monorepo (v1.0)",
          "pr": null,
          "breaking": false,
          "section": "Other"
        }
      ]
    }
  ],
  "roadmap": [
    {
      "number": 83,
      "title": "agent-mcp + browserAutomation: from-anywhere OAuth fix — args only, no Console babysitting",
      "stage": "enhancement",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/83"
    },
    {
      "number": 82,
      "title": "browserAutomation google: Auth Platform client form reliability (empty main, Angular fill, dual URI sections)",
      "stage": "enhancement",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/82"
    },
    {
      "number": 81,
      "title": "browserAutomation google: patch existing Web client redirects + JS origins (no secret rotation)",
      "stage": "enhancement",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/81"
    },
    {
      "number": 66,
      "title": "cf setup: rewrite createApiToken for Cloudflare's new token UI (flow + React-Select permissions/account)",
      "stage": "enhancement",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/66"
    },
    {
      "number": 38,
      "title": "Apply ChatGPT direction review enhancements to inspiration layouts",
      "stage": "enhancement",
      "mark": "⬜",
      "state": "open",
      "url": "https://github.com/VybeKiit/vybekiit/issues/38"
    },
    {
      "number": 37,
      "title": "A/B test landing heroes: before-after, checklist, directors-chair",
      "stage": "v1.0",
      "mark": "⬜",
      "state": "open",
      "url": "https://github.com/VybeKiit/vybekiit/issues/37"
    },
    {
      "number": 36,
      "title": "Production hero: Terminal-to-Live layout with animated agent session demo",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/36"
    },
    {
      "number": 35,
      "title": "Landing inspirations gallery: 10 anti-generic layouts at /inspirations",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/35"
    },
    {
      "number": 20,
      "title": "Build templates/extension (WXT) into a real extension",
      "stage": "v3",
      "mark": "⬜",
      "state": "open",
      "url": "https://github.com/VybeKiit/vybekiit/issues/20"
    },
    {
      "number": 19,
      "title": "Build templates/mobile (Expo) into a real app at web parity",
      "stage": "v2",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/19"
    },
    {
      "number": 17,
      "title": "Publish @vybekiit/* packages to npm (release flow + org)",
      "stage": "needs-secrets",
      "mark": "🧪",
      "state": "open",
      "url": "https://github.com/VybeKiit/vybekiit/issues/17"
    },
    {
      "number": 16,
      "title": "Web template: production-grade component + util foundation (the kit under the screens)",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/16"
    },
    {
      "number": 15,
      "title": "First-run auto-setup: pre-install & wire the must-have CLIs under the hood",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/15"
    },
    {
      "number": 14,
      "title": "Complete the agent skill library (sign-in / data / domain / email / update)",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/14"
    },
    {
      "number": 13,
      "title": "Expand language.md into the canonical plain-language glossary",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/13"
    },
    {
      "number": 8,
      "title": "End-to-end onboarding dry-run: stranger pays → live app in session #1",
      "stage": "money-pipeline",
      "mark": "⬜",
      "state": "open",
      "url": "https://github.com/VybeKiit/vybekiit/issues/8"
    },
    {
      "number": 7,
      "title": "Deploy landing + buyer template to Cloudflare + domain",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/7"
    },
    {
      "number": 6,
      "title": "Flesh out the buyer web app screens end-to-end (home / auth / dashboard)",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/6"
    },
    {
      "number": 5,
      "title": "Provision Supabase: orders table migration + auth",
      "stage": "v1.0",
      "mark": "⬜",
      "state": "open",
      "url": "https://github.com/VybeKiit/vybekiit/issues/5"
    },
    {
      "number": 4,
      "title": "Wire the live Lemon Squeezy → GitHub invite money pipeline",
      "stage": "money-pipeline",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/4"
    },
    {
      "number": 3,
      "title": "Build the landing page (apps/landing): pricing + GitHub-username capture + checkout",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/3"
    },
    {
      "number": 2,
      "title": "Promote templates/web + apps/landing into the workspace + CI gate",
      "stage": "v1.0",
      "mark": "✅",
      "state": "closed",
      "url": "https://github.com/VybeKiit/vybekiit/issues/2"
    }
  ]
} as const satisfies ChangelogData;
