/** Generated by scripts/dev/sync/buildDesignSystemIndex.mjs - do not edit. */
// biome-ignore-all format: generated design-system data stays byte-stable for check mode.
import type { ComponentStateId } from '@library/lib/componentStates';

export interface PrimitiveVariantAxis {
  readonly name: string;
  readonly options: readonly string[];
  readonly defaultOption?: string;
}

export interface PrimitivePropDoc {
  readonly name: string;
  readonly type: string;
  readonly defaultValue?: string;
  readonly description?: string;
}

export interface PrimitiveDescriptor {
  readonly name: string;
  readonly title: string;
  readonly family: string;
  readonly slug: string;
  readonly importPath: string;
  readonly exportName: string;
  readonly axes: readonly PrimitiveVariantAxis[];
  readonly states: readonly ComponentStateId[];
  readonly props: readonly PrimitivePropDoc[];
  readonly hasOverride: boolean;
  readonly sampleChildren: string;
  readonly sampleProps: Readonly<Record<string, string | number | boolean>>;
  readonly sampleClassName: string;
}

export interface PrimitiveFamily {
  readonly name: string;
  readonly order: number;
  readonly primitives: readonly string[];
}

export const DESIGN_SYSTEM_PRIMITIVES = [
  {
    "name": "button",
    "title": "Button",
    "family": "Buttons",
    "slug": "button",
    "importPath": "@vybekiit/ui/button",
    "exportName": "Button",
    "axes": [
      {
        "name": "variant",
        "options": [
          "default",
          "destructive",
          "outline",
          "secondary",
          "ghost",
          "link"
        ],
        "defaultOption": "default"
      },
      {
        "name": "size",
        "options": [
          "default",
          "sm",
          "lg",
          "icon",
          "icon-sm"
        ],
        "defaultOption": "default"
      }
    ],
    "states": [
      "default",
      "disabled"
    ],
    "props": [
      {
        "name": "variant",
        "type": "'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link'",
        "defaultValue": "'default'"
      },
      {
        "name": "size",
        "type": "'default' | 'sm' | 'lg' | 'icon' | 'icon-sm'",
        "defaultValue": "'default'"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "defaultValue": "false"
      }
    ],
    "hasOverride": false,
    "sampleChildren": "Button",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "input",
    "title": "Input",
    "family": "Forms",
    "slug": "input",
    "importPath": "@vybekiit/ui/input",
    "exportName": "Input",
    "axes": [],
    "states": [
      "default",
      "disabled",
      "error",
      "readonly"
    ],
    "props": [
      {
        "name": "type",
        "type": "string",
        "defaultValue": "'text'"
      },
      {
        "name": "placeholder",
        "type": "string"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "defaultValue": "false"
      },
      {
        "name": "aria-invalid",
        "type": "boolean",
        "description": "Drives the error state."
      }
    ],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "textarea",
    "title": "Textarea",
    "family": "Forms",
    "slug": "textarea",
    "importPath": "@vybekiit/ui/textarea",
    "exportName": "Textarea",
    "axes": [],
    "states": [
      "default",
      "disabled",
      "readonly",
      "error"
    ],
    "props": [
      {
        "name": "placeholder",
        "type": "string"
      },
      {
        "name": "disabled",
        "type": "boolean",
        "defaultValue": "false"
      }
    ],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {
      "placeholder": "Write a message…"
    },
    "sampleClassName": "w-full max-w-sm"
  },
  {
    "name": "label",
    "title": "Label",
    "family": "Forms",
    "slug": "label",
    "importPath": "@vybekiit/ui/label",
    "exportName": "Label",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "Email address",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "checkbox",
    "title": "Checkbox",
    "family": "Forms",
    "slug": "checkbox",
    "importPath": "@vybekiit/ui/checkbox",
    "exportName": "Checkbox",
    "axes": [],
    "states": [
      "default",
      "selected",
      "disabled"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "switch",
    "title": "Switch",
    "family": "Forms",
    "slug": "switch",
    "importPath": "@vybekiit/ui/switch",
    "exportName": "Switch",
    "axes": [],
    "states": [
      "default",
      "selected",
      "disabled"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "radio-group",
    "title": "Radio group",
    "family": "Forms",
    "slug": "radio-group",
    "importPath": "@vybekiit/ui/radio-group",
    "exportName": "RadioGroup",
    "axes": [],
    "states": [
      "default",
      "disabled"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "select",
    "title": "Select",
    "family": "Forms",
    "slug": "select",
    "importPath": "@vybekiit/ui/select",
    "exportName": "Select",
    "axes": [],
    "states": [
      "default",
      "disabled"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "dialog",
    "title": "Dialog",
    "family": "Overlays",
    "slug": "dialog",
    "importPath": "@vybekiit/ui/dialog",
    "exportName": "Dialog",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "tooltip",
    "title": "Tooltip",
    "family": "Overlays",
    "slug": "tooltip",
    "importPath": "@vybekiit/ui/tooltip",
    "exportName": "Tooltip",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "table",
    "title": "Table",
    "family": "Data display",
    "slug": "table",
    "importPath": "@vybekiit/ui/table",
    "exportName": "Table",
    "axes": [],
    "states": [
      "default",
      "loading",
      "empty"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "badge",
    "title": "Badge",
    "family": "Data display",
    "slug": "badge",
    "importPath": "@vybekiit/ui/badge",
    "exportName": "Badge",
    "axes": [
      {
        "name": "variant",
        "options": [
          "default",
          "secondary",
          "destructive",
          "outline"
        ],
        "defaultOption": "default"
      }
    ],
    "states": [
      "default"
    ],
    "props": [
      {
        "name": "variant",
        "type": "'default' | 'secondary' | 'destructive' | 'outline'",
        "defaultValue": "'default'"
      }
    ],
    "hasOverride": false,
    "sampleChildren": "Badge",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "avatar",
    "title": "Avatar",
    "family": "Data display",
    "slug": "avatar",
    "importPath": "@vybekiit/ui/avatar",
    "exportName": "Avatar",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "card",
    "title": "Card",
    "family": "Data display",
    "slug": "card",
    "importPath": "@vybekiit/ui/card",
    "exportName": "Card",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "tabs",
    "title": "Tabs",
    "family": "Data display",
    "slug": "tabs",
    "importPath": "@vybekiit/ui/tabs",
    "exportName": "Tabs",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "accordion",
    "title": "Accordion",
    "family": "Data display",
    "slug": "accordion",
    "importPath": "@vybekiit/ui/accordion",
    "exportName": "Accordion",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "kbd",
    "title": "Kbd",
    "family": "Data display",
    "slug": "kbd",
    "importPath": "@vybekiit/ui/kbd",
    "exportName": "Kbd",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "⌘K",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "progress",
    "title": "Progress",
    "family": "Data display",
    "slug": "progress",
    "importPath": "@vybekiit/ui/progress",
    "exportName": "Progress",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {
      "value": 60
    },
    "sampleClassName": "w-64"
  },
  {
    "name": "alert",
    "title": "Alert",
    "family": "Feedback",
    "slug": "alert",
    "importPath": "@vybekiit/ui/alert",
    "exportName": "Alert",
    "axes": [
      {
        "name": "variant",
        "options": [
          "default",
          "destructive",
          "success",
          "warning"
        ],
        "defaultOption": "default"
      }
    ],
    "states": [
      "default"
    ],
    "props": [
      {
        "name": "variant",
        "type": "'default' | 'destructive' | 'success' | 'warning'",
        "defaultValue": "'default'"
      }
    ],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "empty",
    "title": "Empty",
    "family": "Feedback",
    "slug": "empty",
    "importPath": "@vybekiit/ui/empty",
    "exportName": "Empty",
    "axes": [
      {
        "name": "variant",
        "options": [
          "default",
          "dashed",
          "compact"
        ],
        "defaultOption": "default"
      }
    ],
    "states": [
      "empty"
    ],
    "props": [
      {
        "name": "variant",
        "type": "'default' | 'dashed' | 'compact'",
        "defaultValue": "'default'"
      }
    ],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "skeleton",
    "title": "Skeleton",
    "family": "Feedback",
    "slug": "skeleton",
    "importPath": "@vybekiit/ui/skeleton",
    "exportName": "Skeleton",
    "axes": [],
    "states": [
      "loading"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": "h-8 w-48"
  },
  {
    "name": "spinner",
    "title": "Spinner",
    "family": "Feedback",
    "slug": "spinner",
    "importPath": "@vybekiit/ui/spinner",
    "exportName": "Spinner",
    "axes": [],
    "states": [
      "loading"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "separator",
    "title": "Separator",
    "family": "Layout",
    "slug": "separator",
    "importPath": "@vybekiit/ui/separator",
    "exportName": "Separator",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": "w-64"
  },
  {
    "name": "shimmer-button",
    "title": "Shimmer button",
    "family": "Brand",
    "slug": "shimmer-button",
    "importPath": "@vybekiit/ui/shimmer-button",
    "exportName": "ShimmerButton",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "Get started",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "glow-badge",
    "title": "Glow badge",
    "family": "Brand",
    "slug": "glow-badge",
    "importPath": "@vybekiit/ui/glow-badge",
    "exportName": "GlowBadge",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "New",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "gradient-text",
    "title": "Gradient text",
    "family": "Brand",
    "slug": "gradient-text",
    "importPath": "@vybekiit/ui/gradient-text",
    "exportName": "GradientText",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "Ship faster",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "toggle",
    "title": "Toggle",
    "family": "Buttons",
    "slug": "toggle",
    "importPath": "@vybekiit/ui/toggle",
    "exportName": "Toggle",
    "axes": [
      {
        "name": "variant",
        "options": [
          "default",
          "outline"
        ],
        "defaultOption": "default"
      },
      {
        "name": "size",
        "options": [
          "default",
          "sm",
          "lg"
        ],
        "defaultOption": "default"
      }
    ],
    "states": [
      "default",
      "disabled"
    ],
    "props": [
      {
        "name": "variant",
        "type": "'default' | 'outline'",
        "defaultValue": "'default'"
      },
      {
        "name": "size",
        "type": "'default' | 'sm' | 'lg'",
        "defaultValue": "'default'"
      }
    ],
    "hasOverride": false,
    "sampleChildren": "Toggle",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "progress-ring",
    "title": "Progress ring",
    "family": "Feedback",
    "slug": "progress-ring",
    "importPath": "@vybekiit/ui/progress-ring",
    "exportName": "ProgressRing",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {
      "value": 66
    },
    "sampleClassName": ""
  },
  {
    "name": "animated-counter",
    "title": "Animated counter",
    "family": "Data display",
    "slug": "animated-counter",
    "importPath": "@vybekiit/ui/animated-counter",
    "exportName": "AnimatedCounter",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {
      "value": 1240,
      "prefix": "$"
    },
    "sampleClassName": "text-2xl font-bold text-foreground"
  },
  {
    "name": "type-writer",
    "title": "Type writer",
    "family": "Brand",
    "slug": "type-writer",
    "importPath": "@vybekiit/ui/type-writer",
    "exportName": "TypeWriter",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {
      "text": "Ship faster with VybeKiit"
    },
    "sampleClassName": "text-lg text-foreground"
  },
  {
    "name": "vybekiit-logo",
    "title": "VybeKiit mark",
    "family": "Brand",
    "slug": "vybekiit-logo",
    "importPath": "@vybekiit/ui/vybekiit-logo",
    "exportName": "VybeKitMark",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": "h-10 w-10 text-foreground"
  },
  {
    "name": "skeleton-pulse",
    "title": "Skeleton pulse",
    "family": "Feedback",
    "slug": "skeleton-pulse",
    "importPath": "@vybekiit/ui/skeleton-pulse",
    "exportName": "SkeletonPulse",
    "axes": [],
    "states": [
      "loading"
    ],
    "props": [],
    "hasOverride": false,
    "sampleChildren": "",
    "sampleProps": {
      "width": "12rem",
      "height": "2rem"
    },
    "sampleClassName": ""
  },
  {
    "name": "button-group",
    "title": "Button group",
    "family": "Buttons",
    "slug": "button-group",
    "importPath": "@vybekiit/ui/button-group",
    "exportName": "ButtonGroup",
    "axes": [
      {
        "name": "orientation",
        "options": [
          "horizontal",
          "vertical"
        ],
        "defaultOption": "horizontal"
      }
    ],
    "states": [
      "default"
    ],
    "props": [
      {
        "name": "orientation",
        "type": "'horizontal' | 'vertical'",
        "defaultValue": "'horizontal'"
      }
    ],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "toggle-group",
    "title": "Toggle group",
    "family": "Buttons",
    "slug": "toggle-group",
    "importPath": "@vybekiit/ui/toggle-group",
    "exportName": "ToggleGroup",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "field",
    "title": "Field",
    "family": "Forms",
    "slug": "field",
    "importPath": "@vybekiit/ui/field",
    "exportName": "Field",
    "axes": [
      {
        "name": "orientation",
        "options": [
          "vertical",
          "horizontal",
          "responsive"
        ],
        "defaultOption": "vertical"
      }
    ],
    "states": [
      "default",
      "error"
    ],
    "props": [
      {
        "name": "orientation",
        "type": "'vertical' | 'horizontal' | 'responsive'",
        "defaultValue": "'vertical'"
      }
    ],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "input-group",
    "title": "Input group",
    "family": "Forms",
    "slug": "input-group",
    "importPath": "@vybekiit/ui/input-group",
    "exportName": "InputGroup",
    "axes": [
      {
        "name": "align",
        "options": [
          "inline-start",
          "inline-end",
          "block-start",
          "block-end"
        ],
        "defaultOption": "inline-start"
      }
    ],
    "states": [
      "default"
    ],
    "props": [
      {
        "name": "align",
        "type": "'inline-start' | 'inline-end' | 'block-start' | 'block-end'",
        "defaultValue": "'inline-start'"
      }
    ],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "segmented-control",
    "title": "Segmented control",
    "family": "Forms",
    "slug": "segmented-control",
    "importPath": "@vybekiit/ui/segmented-control",
    "exportName": "SegmentedControl",
    "axes": [],
    "states": [
      "default",
      "selected"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "calendar",
    "title": "Calendar",
    "family": "Forms",
    "slug": "calendar",
    "importPath": "@vybekiit/ui/calendar",
    "exportName": "Calendar",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "form",
    "title": "Form",
    "family": "Forms",
    "slug": "form",
    "importPath": "@vybekiit/ui/form",
    "exportName": "Form",
    "axes": [],
    "states": [
      "default",
      "error"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "popover",
    "title": "Popover",
    "family": "Overlays",
    "slug": "popover",
    "importPath": "@vybekiit/ui/popover",
    "exportName": "Popover",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "dropdown-menu",
    "title": "Dropdown menu",
    "family": "Overlays",
    "slug": "dropdown-menu",
    "importPath": "@vybekiit/ui/dropdown-menu",
    "exportName": "DropdownMenu",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "context-menu",
    "title": "Context menu",
    "family": "Overlays",
    "slug": "context-menu",
    "importPath": "@vybekiit/ui/context-menu",
    "exportName": "ContextMenu",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "hover-card",
    "title": "Hover card",
    "family": "Overlays",
    "slug": "hover-card",
    "importPath": "@vybekiit/ui/hover-card",
    "exportName": "HoverCard",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "sheet",
    "title": "Sheet",
    "family": "Overlays",
    "slug": "sheet",
    "importPath": "@vybekiit/ui/sheet",
    "exportName": "Sheet",
    "axes": [
      {
        "name": "side",
        "options": [
          "top",
          "bottom",
          "left",
          "right"
        ],
        "defaultOption": "right"
      }
    ],
    "states": [
      "default"
    ],
    "props": [
      {
        "name": "side",
        "type": "'top' | 'bottom' | 'left' | 'right'",
        "defaultValue": "'right'"
      }
    ],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "drawer",
    "title": "Drawer",
    "family": "Overlays",
    "slug": "drawer",
    "importPath": "@vybekiit/ui/drawer",
    "exportName": "Drawer",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "alert-dialog",
    "title": "Alert dialog",
    "family": "Overlays",
    "slug": "alert-dialog",
    "importPath": "@vybekiit/ui/alert-dialog",
    "exportName": "AlertDialog",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "command",
    "title": "Command",
    "family": "Overlays",
    "slug": "command",
    "importPath": "@vybekiit/ui/command",
    "exportName": "Command",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "carousel",
    "title": "Carousel",
    "family": "Data display",
    "slug": "carousel",
    "importPath": "@vybekiit/ui/carousel",
    "exportName": "Carousel",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "chart",
    "title": "Chart",
    "family": "Data display",
    "slug": "chart",
    "importPath": "@vybekiit/ui/chart",
    "exportName": "ChartContainer",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "kpi",
    "title": "KPI",
    "family": "Data display",
    "slug": "kpi",
    "importPath": "@vybekiit/ui/kpi",
    "exportName": "Kpi",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "icon-box",
    "title": "Icon box",
    "family": "Data display",
    "slug": "icon-box",
    "importPath": "@vybekiit/ui/icon-box",
    "exportName": "IconBox",
    "axes": [
      {
        "name": "size",
        "options": [
          "sm",
          "default",
          "md",
          "lg"
        ],
        "defaultOption": "default"
      },
      {
        "name": "shape",
        "options": [
          "rounded",
          "circle"
        ],
        "defaultOption": "rounded"
      }
    ],
    "states": [
      "default"
    ],
    "props": [
      {
        "name": "size",
        "type": "'sm' | 'default' | 'md' | 'lg'",
        "defaultValue": "'default'"
      },
      {
        "name": "shape",
        "type": "'rounded' | 'circle'",
        "defaultValue": "'rounded'"
      }
    ],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "pulse-beam",
    "title": "Pulse beam",
    "family": "Feedback",
    "slug": "pulse-beam",
    "importPath": "@vybekiit/ui/pulse-beam",
    "exportName": "PulseBeam",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "notification-toast",
    "title": "Notification toast",
    "family": "Feedback",
    "slug": "notification-toast",
    "importPath": "@vybekiit/ui/notification-toast",
    "exportName": "NotificationToast",
    "axes": [],
    "states": [
      "default",
      "success",
      "error"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "step-indicator",
    "title": "Step indicator",
    "family": "Feedback",
    "slug": "step-indicator",
    "importPath": "@vybekiit/ui/step-indicator",
    "exportName": "StepIndicator",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "sonner",
    "title": "Sonner toasts",
    "family": "Feedback",
    "slug": "sonner",
    "importPath": "@vybekiit/ui/sonner",
    "exportName": "Toaster",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "collapsible",
    "title": "Collapsible",
    "family": "Layout",
    "slug": "collapsible",
    "importPath": "@vybekiit/ui/collapsible",
    "exportName": "Collapsible",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "scroll-area",
    "title": "Scroll area",
    "family": "Layout",
    "slug": "scroll-area",
    "importPath": "@vybekiit/ui/scroll-area",
    "exportName": "ScrollArea",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "aspect-ratio",
    "title": "Aspect ratio",
    "family": "Layout",
    "slug": "aspect-ratio",
    "importPath": "@vybekiit/ui/aspect-ratio",
    "exportName": "AspectRatio",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "sidebar",
    "title": "Sidebar",
    "family": "Layout",
    "slug": "sidebar",
    "importPath": "@vybekiit/ui/sidebar",
    "exportName": "Sidebar",
    "axes": [
      {
        "name": "variant",
        "options": [
          "default",
          "outline"
        ],
        "defaultOption": "default"
      },
      {
        "name": "size",
        "options": [
          "default",
          "sm",
          "lg"
        ],
        "defaultOption": "default"
      }
    ],
    "states": [
      "default"
    ],
    "props": [
      {
        "name": "variant",
        "type": "'default' | 'outline'",
        "defaultValue": "'default'"
      },
      {
        "name": "size",
        "type": "'default' | 'sm' | 'lg'",
        "defaultValue": "'default'"
      }
    ],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "glow-card",
    "title": "Glow card",
    "family": "Brand",
    "slug": "glow-card",
    "importPath": "@vybekiit/ui/glow-card",
    "exportName": "GlowCard",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "AutoScrollRow",
    "title": "Auto scroll row",
    "family": "Brand",
    "slug": "AutoScrollRow",
    "importPath": "@vybekiit/ui/AutoScrollRow",
    "exportName": "AutoScrollRow",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "terminal-block",
    "title": "Terminal block",
    "family": "Brand",
    "slug": "terminal-block",
    "importPath": "@vybekiit/ui/terminal-block",
    "exportName": "TerminalBlock",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "agent-avatar",
    "title": "Agent avatar",
    "family": "Brand",
    "slug": "agent-avatar",
    "importPath": "@vybekiit/ui/agent-avatar",
    "exportName": "AgentAvatar",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "agent-logo",
    "title": "Agent logo",
    "family": "Brand",
    "slug": "agent-logo",
    "importPath": "@vybekiit/ui/agent-logo",
    "exportName": "AgentLogo",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "provider-mark",
    "title": "Provider mark",
    "family": "Brand",
    "slug": "provider-mark",
    "importPath": "@vybekiit/ui/provider-mark",
    "exportName": "ProviderMark",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "logo-grid",
    "title": "Logo grid",
    "family": "Brand",
    "slug": "logo-grid",
    "importPath": "@vybekiit/ui/logo-grid",
    "exportName": "LogoGrid",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "domain-journey-card",
    "title": "Domain journey card",
    "family": "Brand",
    "slug": "domain-journey-card",
    "importPath": "@vybekiit/ui/domain-journey-card",
    "exportName": "DomainJourneyCard",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "journey-rail",
    "title": "Journey rail",
    "family": "Brand",
    "slug": "journey-rail",
    "importPath": "@vybekiit/ui/journey-rail",
    "exportName": "JourneyRail",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  },
  {
    "name": "floating-panel",
    "title": "Floating panel",
    "family": "Brand",
    "slug": "floating-panel",
    "importPath": "@vybekiit/ui/floating-panel",
    "exportName": "FloatingPanel",
    "axes": [],
    "states": [
      "default"
    ],
    "props": [],
    "hasOverride": true,
    "sampleChildren": "",
    "sampleProps": {},
    "sampleClassName": ""
  }
] as const satisfies readonly PrimitiveDescriptor[];

export const DESIGN_SYSTEM_FAMILIES = [
  {
    "name": "Buttons",
    "order": 0,
    "primitives": [
      "button",
      "toggle",
      "button-group",
      "toggle-group"
    ]
  },
  {
    "name": "Forms",
    "order": 1,
    "primitives": [
      "input",
      "textarea",
      "label",
      "checkbox",
      "switch",
      "radio-group",
      "select",
      "field",
      "input-group",
      "segmented-control",
      "calendar",
      "form"
    ]
  },
  {
    "name": "Overlays",
    "order": 2,
    "primitives": [
      "dialog",
      "tooltip",
      "popover",
      "dropdown-menu",
      "context-menu",
      "hover-card",
      "sheet",
      "drawer",
      "alert-dialog",
      "command"
    ]
  },
  {
    "name": "Data display",
    "order": 3,
    "primitives": [
      "table",
      "badge",
      "avatar",
      "card",
      "tabs",
      "accordion",
      "kbd",
      "progress",
      "animated-counter",
      "carousel",
      "chart",
      "kpi",
      "icon-box"
    ]
  },
  {
    "name": "Feedback",
    "order": 4,
    "primitives": [
      "alert",
      "empty",
      "skeleton",
      "spinner",
      "progress-ring",
      "skeleton-pulse",
      "pulse-beam",
      "notification-toast",
      "step-indicator",
      "sonner"
    ]
  },
  {
    "name": "Layout",
    "order": 5,
    "primitives": [
      "separator",
      "collapsible",
      "scroll-area",
      "aspect-ratio",
      "sidebar"
    ]
  },
  {
    "name": "Brand",
    "order": 6,
    "primitives": [
      "shimmer-button",
      "glow-badge",
      "gradient-text",
      "type-writer",
      "vybekiit-logo",
      "glow-card",
      "AutoScrollRow",
      "terminal-block",
      "agent-avatar",
      "agent-logo",
      "provider-mark",
      "logo-grid",
      "domain-journey-card",
      "journey-rail",
      "floating-panel"
    ]
  }
] as const satisfies readonly PrimitiveFamily[];

export const PRIMITIVE_BY_SLUG = Object.fromEntries(
  DESIGN_SYSTEM_PRIMITIVES.map((primitive) => [primitive.slug, primitive]),
) as Record<string, PrimitiveDescriptor>;
