/** Generated by scripts/dev/sync/buildDesignSystemIndex.mjs - do not edit. */
// biome-ignore-all format: generated registry stays byte-stable for check mode.
// biome-ignore-all assist/source/organizeImports: generated registry preserves display order.
'use client';
import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';
import { Button } from '@vybekiit/ui/button';
import { Textarea } from '@vybekiit/ui/textarea';
import { Label } from '@vybekiit/ui/label';
import { Badge } from '@vybekiit/ui/badge';
import { Kbd } from '@vybekiit/ui/kbd';
import { Progress } from '@vybekiit/ui/progress';
import { Skeleton } from '@vybekiit/ui/skeleton';
import { Spinner } from '@vybekiit/ui/spinner';
import { Separator } from '@vybekiit/ui/separator';
import { ShimmerButton } from '@vybekiit/ui/shimmer-button';
import { GlowBadge } from '@vybekiit/ui/glow-badge';
import { GradientText } from '@vybekiit/ui/gradient-text';
import { Toggle } from '@vybekiit/ui/toggle';
import { ProgressRing } from '@vybekiit/ui/progress-ring';
import { AnimatedCounter } from '@vybekiit/ui/animated-counter';
import { TypeWriter } from '@vybekiit/ui/type-writer';
import { VybeKitMark } from '@vybekiit/ui/vybekiit-logo';
import { SkeletonPulse } from '@vybekiit/ui/skeleton-pulse';

/** Shown while a lazily-loaded override gallery chunk resolves. */
const OverrideFallback = () => null;

/** Raw primitives rendered by the auto playground (no override needed). */
export const PRIMITIVE_AUTO_COMPONENTS: Readonly<Record<string, ComponentType<Record<string, unknown>>>> = {
  'button': Button as unknown as ComponentType<Record<string, unknown>>,
  'textarea': Textarea as unknown as ComponentType<Record<string, unknown>>,
  'label': Label as unknown as ComponentType<Record<string, unknown>>,
  'badge': Badge as unknown as ComponentType<Record<string, unknown>>,
  'kbd': Kbd as unknown as ComponentType<Record<string, unknown>>,
  'progress': Progress as unknown as ComponentType<Record<string, unknown>>,
  'skeleton': Skeleton as unknown as ComponentType<Record<string, unknown>>,
  'spinner': Spinner as unknown as ComponentType<Record<string, unknown>>,
  'separator': Separator as unknown as ComponentType<Record<string, unknown>>,
  'shimmer-button': ShimmerButton as unknown as ComponentType<Record<string, unknown>>,
  'glow-badge': GlowBadge as unknown as ComponentType<Record<string, unknown>>,
  'gradient-text': GradientText as unknown as ComponentType<Record<string, unknown>>,
  'toggle': Toggle as unknown as ComponentType<Record<string, unknown>>,
  'progress-ring': ProgressRing as unknown as ComponentType<Record<string, unknown>>,
  'animated-counter': AnimatedCounter as unknown as ComponentType<Record<string, unknown>>,
  'type-writer': TypeWriter as unknown as ComponentType<Record<string, unknown>>,
  'vybekiit-logo': VybeKitMark as unknown as ComponentType<Record<string, unknown>>,
  'skeleton-pulse': SkeletonPulse as unknown as ComponentType<Record<string, unknown>>,
};

/** Hand-authored live galleries, lazy per-primitive so a slug only compiles its own chunk. */
export const PRIMITIVE_OVERRIDE_COMPONENTS: Readonly<Record<string, ComponentType>> = {
  'input': dynamic(() => import('@library/stories/vybekiit/input').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'checkbox': dynamic(() => import('@library/stories/vybekiit/checkbox').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'switch': dynamic(() => import('@library/stories/vybekiit/switch').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'radio-group': dynamic(() => import('@library/stories/vybekiit/radio-group').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'select': dynamic(() => import('@library/stories/vybekiit/select').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'dialog': dynamic(() => import('@library/stories/vybekiit/dialog').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'tooltip': dynamic(() => import('@library/stories/vybekiit/tooltip').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'table': dynamic(() => import('@library/stories/vybekiit/table').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'avatar': dynamic(() => import('@library/stories/vybekiit/avatar').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'card': dynamic(() => import('@library/stories/vybekiit/card').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'tabs': dynamic(() => import('@library/stories/vybekiit/tabs').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'accordion': dynamic(() => import('@library/stories/vybekiit/accordion').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'alert': dynamic(() => import('@library/stories/vybekiit/alert').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'empty': dynamic(() => import('@library/stories/vybekiit/empty').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'button-group': dynamic(() => import('@library/stories/vybekiit/button-group').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'toggle-group': dynamic(() => import('@library/stories/vybekiit/toggle-group').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'field': dynamic(() => import('@library/stories/vybekiit/field').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'input-group': dynamic(() => import('@library/stories/vybekiit/input-group').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'segmented-control': dynamic(() => import('@library/stories/vybekiit/segmented-control').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'calendar': dynamic(() => import('@library/stories/vybekiit/calendar').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'form': dynamic(() => import('@library/stories/vybekiit/form').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'popover': dynamic(() => import('@library/stories/vybekiit/popover').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'dropdown-menu': dynamic(() => import('@library/stories/vybekiit/dropdown-menu').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'context-menu': dynamic(() => import('@library/stories/vybekiit/context-menu').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'hover-card': dynamic(() => import('@library/stories/vybekiit/hover-card').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'sheet': dynamic(() => import('@library/stories/vybekiit/sheet').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'drawer': dynamic(() => import('@library/stories/vybekiit/drawer').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'alert-dialog': dynamic(() => import('@library/stories/vybekiit/alert-dialog').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'command': dynamic(() => import('@library/stories/vybekiit/command').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'carousel': dynamic(() => import('@library/stories/vybekiit/carousel').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'chart': dynamic(() => import('@library/stories/vybekiit/chart').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'kpi': dynamic(() => import('@library/stories/vybekiit/kpi').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'icon-box': dynamic(() => import('@library/stories/vybekiit/icon-box').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'pulse-beam': dynamic(() => import('@library/stories/vybekiit/pulse-beam').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'notification-toast': dynamic(() => import('@library/stories/vybekiit/notification-toast').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'step-indicator': dynamic(() => import('@library/stories/vybekiit/step-indicator').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'sonner': dynamic(() => import('@library/stories/vybekiit/sonner').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'collapsible': dynamic(() => import('@library/stories/vybekiit/collapsible').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'scroll-area': dynamic(() => import('@library/stories/vybekiit/scroll-area').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'aspect-ratio': dynamic(() => import('@library/stories/vybekiit/aspect-ratio').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'sidebar': dynamic(() => import('@library/stories/vybekiit/sidebar').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'glow-card': dynamic(() => import('@library/stories/vybekiit/glow-card').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'AutoScrollRow': dynamic(() => import('@library/stories/vybekiit/AutoScrollRow').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'terminal-block': dynamic(() => import('@library/stories/vybekiit/terminal-block').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'agent-avatar': dynamic(() => import('@library/stories/vybekiit/agent-avatar').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'agent-logo': dynamic(() => import('@library/stories/vybekiit/agent-logo').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'provider-mark': dynamic(() => import('@library/stories/vybekiit/provider-mark').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'logo-grid': dynamic(() => import('@library/stories/vybekiit/logo-grid').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'domain-journey-card': dynamic(() => import('@library/stories/vybekiit/domain-journey-card').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'journey-rail': dynamic(() => import('@library/stories/vybekiit/journey-rail').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
  'floating-panel': dynamic(() => import('@library/stories/vybekiit/floating-panel').then((m) => ({ default: m.default.ShowAll })), { ssr: false, loading: OverrideFallback }),
};
