/** Generated by scripts/dev/sync/buildPageRecipeIndex.mjs - do not edit. */
// biome-ignore-all format: generated registry stays byte-stable for check mode.
// biome-ignore-all assist/source/organizeImports: generated registry preserves manifest order.
import type { ComponentType } from 'react';

import { OnboardingPage as OnboardingPageRecipe } from '../pageRecipes/onboardingPage';
import { IdeaPlannerPage as IdeaPlannerPageRecipe } from '../pageRecipes/ideaPlannerPage';
import { AuthPage as AuthPageRecipe } from '../pageRecipes/authPage';
import { PricingPage as PricingPageRecipe } from '../pageRecipes/pricingPage';
import { LaunchChecklistPage as LaunchChecklistPageRecipe } from '../pageRecipes/launchChecklistPage';
import { FileManagerPage as FileManagerPageRecipe } from '../pageRecipes/fileManagerPage';
import { EmailNotificationsPage as EmailNotificationsPageRecipe } from '../pageRecipes/emailNotificationsPage';
import { TeamsPage as TeamsPageRecipe } from '../pageRecipes/teamsPage';
import { AnalyticsPage as AnalyticsPageRecipe } from '../pageRecipes/analyticsPage';
import { AiAssistantPage as AiAssistantPageRecipe } from '../pageRecipes/aiAssistantPage';
import { SearchPage as SearchPageRecipe } from '../pageRecipes/searchPage';
import { RealtimePage as RealtimePageRecipe } from '../pageRecipes/realtimePage';
import { BlogPage as BlogPageRecipe } from '../pageRecipes/blogPage';
import { SafetyPage as SafetyPageRecipe } from '../pageRecipes/safetyPage';
import { BrandAssetsPage as BrandAssetsPageRecipe } from '../pageRecipes/brandAssetsPage';
import { LanguagePage as LanguagePageRecipe } from '../pageRecipes/languagePage';
import { FeatureFlagsPage as FeatureFlagsPageRecipe } from '../pageRecipes/featureFlagsPage';

export const PAGE_RECIPE_COMPONENTS = {
  'onboarding': OnboardingPageRecipe,
  'idea-planner': IdeaPlannerPageRecipe,
  'auth': AuthPageRecipe,
  'pricing': PricingPageRecipe,
  'launch-checklist': LaunchChecklistPageRecipe,
  'file-manager': FileManagerPageRecipe,
  'email-notifications': EmailNotificationsPageRecipe,
  'teams': TeamsPageRecipe,
  'analytics': AnalyticsPageRecipe,
  'ai-assistant': AiAssistantPageRecipe,
  'search': SearchPageRecipe,
  'realtime': RealtimePageRecipe,
  'blog': BlogPageRecipe,
  'safety': SafetyPageRecipe,
  'brand-assets': BrandAssetsPageRecipe,
  'language': LanguagePageRecipe,
  'feature-flags': FeatureFlagsPageRecipe,
} as Record<string, ComponentType>;
