/** Generated by scripts/dev/sync/buildPageRecipeIndex.mjs - do not edit. */
// biome-ignore-all format: generated group summaries stay byte-stable for check mode.

export interface PageRecipeGroupSummary {
  readonly id: string;
  readonly label: string;
  readonly count: number;
}

export const PAGE_RECIPE_GROUP_SUMMARIES = [
  {
    "id": "onboarding",
    "label": "Onboarding",
    "count": 1
  },
  {
    "id": "idea-planning",
    "label": "Idea Planning",
    "count": 1
  },
  {
    "id": "dashboard-home",
    "label": "Dashboard Home",
    "count": 2
  },
  {
    "id": "auth",
    "label": "Auth",
    "count": 1
  },
  {
    "id": "legal",
    "label": "Legal",
    "count": 2
  },
  {
    "id": "account-settings",
    "label": "Account Settings",
    "count": 2
  },
  {
    "id": "payments",
    "label": "Payments",
    "count": 1
  },
  {
    "id": "commerce",
    "label": "Commerce",
    "count": 5
  },
  {
    "id": "launch",
    "label": "Launch",
    "count": 1
  },
  {
    "id": "files",
    "label": "Files",
    "count": 1
  },
  {
    "id": "communication",
    "label": "Communication",
    "count": 2
  },
  {
    "id": "support",
    "label": "Support",
    "count": 1
  },
  {
    "id": "integrations",
    "label": "Integrations",
    "count": 1
  },
  {
    "id": "teams",
    "label": "Teams",
    "count": 1
  },
  {
    "id": "analytics",
    "label": "Analytics",
    "count": 1
  },
  {
    "id": "admin",
    "label": "Admin",
    "count": 6
  },
  {
    "id": "crm",
    "label": "CRM",
    "count": 3
  },
  {
    "id": "ai",
    "label": "AI",
    "count": 1
  },
  {
    "id": "search",
    "label": "Search",
    "count": 1
  },
  {
    "id": "realtime",
    "label": "Realtime",
    "count": 1
  },
  {
    "id": "productivity",
    "label": "Productivity",
    "count": 2
  },
  {
    "id": "blog",
    "label": "Blog",
    "count": 1
  },
  {
    "id": "content-platform",
    "label": "Content Platform",
    "count": 4
  },
  {
    "id": "safety",
    "label": "Safety",
    "count": 1
  },
  {
    "id": "brand-assets",
    "label": "Brand Assets",
    "count": 1
  },
  {
    "id": "language",
    "label": "Language",
    "count": 1
  },
  {
    "id": "feature-flags",
    "label": "Feature Flags",
    "count": 1
  }
] as const satisfies readonly PageRecipeGroupSummary[];
