/** Generated by scripts/dev/sync/buildPageRecipeIndex.mjs - do not edit. */
// biome-ignore-all format: generated registry stays byte-stable for check mode.
// biome-ignore-all assist/source/organizeImports: generated registry preserves manifest order.
import type { ComponentType } from 'react';

import { OnboardingPage } from '@library/pageRecipes/OnboardingPage/OnboardingPage';
import { IdeaPlannerPage } from '@library/pageRecipes/IdeaPlannerPage';
import { DashboardHomePage } from '@library/pageRecipes/DashboardHomePage/DashboardHomePage';
import { CommandCenterPage } from '@library/pageRecipes/CommandCenterPage/CommandCenterPage';
import { AuthPage } from '@library/pageRecipes/AuthPage/AuthPage';
import { TermsOfServicePage } from '@library/pageRecipes/TermsOfServicePage';
import { PrivacyPolicyPage } from '@library/pageRecipes/PrivacyPolicyPage';
import { UserSettingsPage } from '@library/pageRecipes/UserSettingsPage';
import { AccountSecurityPage } from '@library/pageRecipes/AccountSecurityPage';
import { PricingPage } from '@library/pageRecipes/PricingPage/PricingPage';
import { ProductGridPage } from '@library/pageRecipes/ProductGridPage';
import { ProductDetailPage } from '@library/pageRecipes/ProductDetailPage/ProductDetailPage';
import { CartPage } from '@library/pageRecipes/CartPage/CartPage';
import { CheckoutPage } from '@library/pageRecipes/CheckoutPage/CheckoutPage';
import { OrdersPage } from '@library/pageRecipes/OrdersPage';
import { LaunchChecklistPage } from '@library/pageRecipes/LaunchChecklistPage';
import { FileManagerPage } from '@library/pageRecipes/FileManagerPage';
import { EmailNotificationsPage } from '@library/pageRecipes/EmailNotificationsPage';
import { NotificationsCenterPage } from '@library/pageRecipes/NotificationsCenterPage/NotificationsCenterPage';
import { SupportCenterPage } from '@library/pageRecipes/SupportCenterPage';
import { IntegrationsPage } from '@library/pageRecipes/IntegrationsPage';
import { TeamsPage } from '@library/pageRecipes/TeamsPage';
import { AnalyticsPage } from '@library/pageRecipes/AnalyticsPage/AnalyticsPage';
import { AdminPanelPage } from '@library/pageRecipes/AdminPanelPage';
import { UserManagementPage } from '@library/pageRecipes/UserManagementPage';
import { AuditLogPage } from '@library/pageRecipes/AuditLogPage';
import { BillingAdminPage } from '@library/pageRecipes/BillingAdminPage/BillingAdminPage';
import { SystemHealthPage } from '@library/pageRecipes/SystemHealthPage';
import { RolePermissionsPage } from '@library/pageRecipes/RolePermissionsPage';
import { CustomersPage } from '@library/pageRecipes/CustomersPage/CustomersPage';
import { CustomerDetailPage } from '@library/pageRecipes/CustomerDetailPage/CustomerDetailPage';
import { PipelinePage } from '@library/pageRecipes/PipelinePage/PipelinePage';
import { AiAssistantPage } from '@library/pageRecipes/AiAssistantPage';
import { SearchPage } from '@library/pageRecipes/SearchPage';
import { RealtimePage } from '@library/pageRecipes/RealtimePage';
import { TasksPage } from '@library/pageRecipes/TasksPage';
import { CalendarPage } from '@library/pageRecipes/CalendarPage';
import { BlogPage } from '@library/pageRecipes/BlogPage';
import { MediaGalleryPage } from '@library/pageRecipes/MediaGalleryPage';
import { DocsPage } from '@library/pageRecipes/DocsPage/DocsPage';
import { StatusPage } from '@library/pageRecipes/StatusPage';
import { ChangelogPage } from '@library/pageRecipes/ChangelogPage';
import { SafetyPage } from '@library/pageRecipes/SafetyPage';
import { BrandAssetsPage } from '@library/pageRecipes/BrandAssetsPage';
import { LanguagePage } from '@library/pageRecipes/LanguagePage';
import { FeatureFlagsPage } from '@library/pageRecipes/FeatureFlagsPage/FeatureFlagsPage';

export const PAGE_RECIPE_COMPONENTS: Readonly<Record<string, ComponentType>> = {
  'onboarding': OnboardingPage,
  'idea-planner': IdeaPlannerPage,
  'dashboard-home': DashboardHomePage,
  'command-center': CommandCenterPage,
  'auth': AuthPage,
  'terms-of-service': TermsOfServicePage,
  'privacy-policy': PrivacyPolicyPage,
  'user-settings': UserSettingsPage,
  'account-security': AccountSecurityPage,
  'pricing': PricingPage,
  'product-grid': ProductGridPage,
  'product-detail': ProductDetailPage,
  'cart': CartPage,
  'checkout': CheckoutPage,
  'orders': OrdersPage,
  'launch-checklist': LaunchChecklistPage,
  'file-manager': FileManagerPage,
  'email-notifications': EmailNotificationsPage,
  'notifications-center': NotificationsCenterPage,
  'support-center': SupportCenterPage,
  'integrations': IntegrationsPage,
  'teams': TeamsPage,
  'analytics': AnalyticsPage,
  'admin-panel': AdminPanelPage,
  'user-management': UserManagementPage,
  'audit-log': AuditLogPage,
  'billing-admin': BillingAdminPage,
  'system-health': SystemHealthPage,
  'role-permissions': RolePermissionsPage,
  'customers': CustomersPage,
  'customer-detail': CustomerDetailPage,
  'pipeline': PipelinePage,
  'ai-assistant': AiAssistantPage,
  'search': SearchPage,
  'realtime': RealtimePage,
  'tasks': TasksPage,
  'calendar': CalendarPage,
  'blog': BlogPage,
  'media-gallery': MediaGalleryPage,
  'docs': DocsPage,
  'status': StatusPage,
  'changelog': ChangelogPage,
  'safety': SafetyPage,
  'brand-assets': BrandAssetsPage,
  'language': LanguagePage,
  'feature-flags': FeatureFlagsPage,
};
