/** Generated by scripts/dev/sync/buildPageRecipeIndex.mjs - do not edit. */
// biome-ignore-all format: generated registry stays byte-stable for check mode.
// biome-ignore-all assist/source/organizeImports: generated registry preserves manifest order.
import type { ComponentType } from 'react';

import { OnboardingPage as OnboardingPageRecipe } from '../pageRecipes/OnboardingPage';
import { IdeaPlannerPage as IdeaPlannerPageRecipe } from '../pageRecipes/IdeaPlannerPage';
import { DashboardHomePage as DashboardHomePageRecipe } from '../pageRecipes/DashboardHomePage';
import { CommandCenterPage as CommandCenterPageRecipe } from '../pageRecipes/CommandCenterPage';
import { AuthPage as AuthPageRecipe } from '../pageRecipes/AuthPage';
import { TermsOfServicePage as TermsOfServicePageRecipe } from '../pageRecipes/TermsOfServicePage';
import { PrivacyPolicyPage as PrivacyPolicyPageRecipe } from '../pageRecipes/PrivacyPolicyPage';
import { UserSettingsPage as UserSettingsPageRecipe } from '../pageRecipes/UserSettingsPage';
import { AccountSecurityPage as AccountSecurityPageRecipe } from '../pageRecipes/AccountSecurityPage';
import { PricingPage as PricingPageRecipe } from '../pageRecipes/PricingPage';
import { ProductGridPage as ProductGridPageRecipe } from '../pageRecipes/ProductGridPage';
import { ProductDetailPage as ProductDetailPageRecipe } from '../pageRecipes/ProductDetailPage';
import { CartPage as CartPageRecipe } from '../pageRecipes/CartPage';
import { CheckoutPage as CheckoutPageRecipe } from '../pageRecipes/CheckoutPage';
import { OrdersPage as OrdersPageRecipe } from '../pageRecipes/OrdersPage';
import { LaunchChecklistPage as LaunchChecklistPageRecipe } from '../pageRecipes/LaunchChecklistPage';
import { FileManagerPage as FileManagerPageRecipe } from '../pageRecipes/FileManagerPage';
import { EmailNotificationsPage as EmailNotificationsPageRecipe } from '../pageRecipes/EmailNotificationsPage';
import { NotificationsCenterPage as NotificationsCenterPageRecipe } from '../pageRecipes/NotificationsCenterPage';
import { SupportCenterPage as SupportCenterPageRecipe } from '../pageRecipes/SupportCenterPage';
import { IntegrationsPage as IntegrationsPageRecipe } from '../pageRecipes/IntegrationsPage';
import { TeamsPage as TeamsPageRecipe } from '../pageRecipes/TeamsPage';
import { AnalyticsPage as AnalyticsPageRecipe } from '../pageRecipes/AnalyticsPage';
import { AdminPanelPage as AdminPanelPageRecipe } from '../pageRecipes/AdminPanelPage';
import { UserManagementPage as UserManagementPageRecipe } from '../pageRecipes/UserManagementPage';
import { AuditLogPage as AuditLogPageRecipe } from '../pageRecipes/AuditLogPage';
import { BillingAdminPage as BillingAdminPageRecipe } from '../pageRecipes/BillingAdminPage';
import { SystemHealthPage as SystemHealthPageRecipe } from '../pageRecipes/SystemHealthPage';
import { RolePermissionsPage as RolePermissionsPageRecipe } from '../pageRecipes/RolePermissionsPage';
import { CustomersPage as CustomersPageRecipe } from '../pageRecipes/CustomersPage';
import { CustomerDetailPage as CustomerDetailPageRecipe } from '../pageRecipes/CustomerDetailPage';
import { PipelinePage as PipelinePageRecipe } from '../pageRecipes/PipelinePage';
import { AiAssistantPage as AiAssistantPageRecipe } from '../pageRecipes/AiAssistantPage';
import { SearchPage as SearchPageRecipe } from '../pageRecipes/SearchPage';
import { RealtimePage as RealtimePageRecipe } from '../pageRecipes/RealtimePage';
import { TasksPage as TasksPageRecipe } from '../pageRecipes/TasksPage';
import { CalendarPage as CalendarPageRecipe } from '../pageRecipes/CalendarPage';
import { BlogPage as BlogPageRecipe } from '../pageRecipes/BlogPage';
import { MediaGalleryPage as MediaGalleryPageRecipe } from '../pageRecipes/MediaGalleryPage';
import { DocsPage as DocsPageRecipe } from '../pageRecipes/DocsPage';
import { StatusPage as StatusPageRecipe } from '../pageRecipes/StatusPage';
import { ChangelogPage as ChangelogPageRecipe } from '../pageRecipes/ChangelogPage';
import { SafetyPage as SafetyPageRecipe } from '../pageRecipes/SafetyPage';
import { BrandAssetsPage as BrandAssetsPageRecipe } from '../pageRecipes/BrandAssetsPage';
import { LanguagePage as LanguagePageRecipe } from '../pageRecipes/LanguagePage';
import { FeatureFlagsPage as FeatureFlagsPageRecipe } from '../pageRecipes/FeatureFlagsPage';

export const PAGE_RECIPE_COMPONENTS = {
  'onboarding': OnboardingPageRecipe,
  'idea-planner': IdeaPlannerPageRecipe,
  'dashboard-home': DashboardHomePageRecipe,
  'command-center': CommandCenterPageRecipe,
  'auth': AuthPageRecipe,
  'terms-of-service': TermsOfServicePageRecipe,
  'privacy-policy': PrivacyPolicyPageRecipe,
  'user-settings': UserSettingsPageRecipe,
  'account-security': AccountSecurityPageRecipe,
  'pricing': PricingPageRecipe,
  'product-grid': ProductGridPageRecipe,
  'product-detail': ProductDetailPageRecipe,
  'cart': CartPageRecipe,
  'checkout': CheckoutPageRecipe,
  'orders': OrdersPageRecipe,
  'launch-checklist': LaunchChecklistPageRecipe,
  'file-manager': FileManagerPageRecipe,
  'email-notifications': EmailNotificationsPageRecipe,
  'notifications-center': NotificationsCenterPageRecipe,
  'support-center': SupportCenterPageRecipe,
  'integrations': IntegrationsPageRecipe,
  'teams': TeamsPageRecipe,
  'analytics': AnalyticsPageRecipe,
  'admin-panel': AdminPanelPageRecipe,
  'user-management': UserManagementPageRecipe,
  'audit-log': AuditLogPageRecipe,
  'billing-admin': BillingAdminPageRecipe,
  'system-health': SystemHealthPageRecipe,
  'role-permissions': RolePermissionsPageRecipe,
  'customers': CustomersPageRecipe,
  'customer-detail': CustomerDetailPageRecipe,
  'pipeline': PipelinePageRecipe,
  'ai-assistant': AiAssistantPageRecipe,
  'search': SearchPageRecipe,
  'realtime': RealtimePageRecipe,
  'tasks': TasksPageRecipe,
  'calendar': CalendarPageRecipe,
  'blog': BlogPageRecipe,
  'media-gallery': MediaGalleryPageRecipe,
  'docs': DocsPageRecipe,
  'status': StatusPageRecipe,
  'changelog': ChangelogPageRecipe,
  'safety': SafetyPageRecipe,
  'brand-assets': BrandAssetsPageRecipe,
  'language': LanguagePageRecipe,
  'feature-flags': FeatureFlagsPageRecipe,
} as Record<string, ComponentType>;
